### ISSUE TITLE
Fix DecoderOptions.parse

### ISSUE THREAD

**Issue by relud** [mozilla/gcp-ingestion#101]
An exception occured while executing the Java class. Method [parse] has multiple definitions [public static com.mozilla.telemetry.decoder.DecoderOptions$Parsed com .mozilla.telemetry.decoder.DecoderOptions.parse(com.mozilla.telemetry.decoder.DecoderOptions), public static com.mozilla.telemetry.options.SinkOptions$Parsed com.mozilla.telemetry.options.SinkOptions.parse(com.mozilla.telemetry.options.SinkOptions)] with different return types for [com.mozilla.telemetry.decoder.DecoderOptions]. -> [Help 1]

**Comment by jklukas** [comment]
I was able to reproduce by running the example in the README for running Decoder. I will resolve this and add a test that actually invokes the Decoder.
