### ISSUE TITLE
Backfill structured live/stable tables for 2019-12-07

### ISSUE THREAD

**Issue by whd** [mozilla/gcp-ingestion#1040]
/CC @jklukas 

This happened on a weekend and I forgot to follow up. While working with :relud on some k8s sink verification stuff I noticed this job was still running/draining and canceled it today (Dec. 17th). (Side note: this is he job for the live tables, not the decoded tables, so my original hypothesis that this could be the cause of some PBD discrepancies we were seeing is unlikely.)

The size of gs://moz-fx-data-prod-dataflow/bqsink/201911201514_993f9de/tmp indicates about 125GB of data is missing.

Being ultra conservative, we might consider also reprocessing December 10 and 14 since [this graph that I can't seem to save on a dashboard](https://app.google.stackdriver.com/metrics-explorer?isAutoRefresh=false&project=moz-fx-data-ingesti-prod-579d&timeSelection=%7B%22timeRange%22:%221m%22%7D&xZoomDomain=%7B%22start%22:%222019-12-09T02:21:48.596Z%22,%22end%22:%222019-12-18T02:38:36.037Z%22%7D&xyChart=%7B%22dataSets%22:%5B%7B%22timeSeriesFilter%22:%7B%22filter%22:%22metric.type%3D%5C%22dataflow.googleapis.com%2Fjob%2Felements_produced_count%5C%22%20resource.type%3D%5C%22dataflow_job%5C%22%20resource.label.%5C%22project_id%5C%22%3D%5C%22moz-fx-data-beam-prod-11f7%5C%22%20metric.label.%5C%22job_id%5C%22%3D%5C%222019-12-06_01_03_28-10856724101763540891%5C%22%20metric.label.%5C%22ptransform%5C%22%3Dmonitoring.regex.full_match(%5C%22.*ubsub.*%5C%22)%22,%22perSeriesAligner%22:%22ALIGN_RATE%22,%22crossSeriesReducer%22:%22REDUCE_NONE%22,%22secondaryCrossSeriesReducer%22:%22REDUCE_NONE%22,%22minAlignmentPeriod%22:%2260s%22,%22groupByFields%22:%5B%22metric.label.%5C%22ptransform%5C%22%22%5D,%22unitOverride%22:%221%22%7D,%22targetAxis%22:%22Y1%22,%22plotType%22:%22LINE%22%7D%5D,%22options%22:%7B%22mode%22:%22COLOR%22%7D,%22constantLines%22:%5B%5D,%22timeshiftDuration%22:%220s%22,%22y1Axis%22:%7B%22label%22:%22y1Axis%22,%22scale%22:%22LINEAR%22%7D%7D) suggests that a single pubsub read api call was made by the stuck job on each of those days.

**Comment by jklukas** [comment]
I've launched a backfill job to pull data from query: 
```
SELECT * FROM \`moz-fx-data-shared-prod.payload_bytes_decoded.structured_*\` WHERE DATE(submission_timestamp) IN (DATE '2019-12-07', DATE '2019-12-10', DATE '2019-12-14')
```

So this will hit all 3 days affected. I'll copy the results into live tables, then rerun copy_dedupe and downstream ETL in Airflow.

**Comment by jklukas** [comment]
Backfill is complete. Running ETL now.

**Comment by jklukas** [comment]
ETL backfill is complete.
