### ISSUE TITLE
GeoLite2 no longer available through public download link

### ISSUE THREAD

**Issue by acmiyaguchi** [mozilla/gcp-ingestion#1054]
https://github.com/mozilla/gcp-ingestion/blob/036d268fd46daa8220c5fc8d326a013ecafcd006/ingestion-beam/bin/download-geolite2#L8

https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

As of 2019-12-30, this public download link will no longer work. Instead, a user will need to register for an account and use one of the methods [on this page](https://dev.maxmind.com/geoip/geoipupdate/#Direct_Downloads) to get a copy of the database.

**Comment by jklukas** [comment]
Note that CI does not depend on the GeoLite2 DB, so this only affects users attempting to run the Decoder locally. But indeed it means that the currently documented instructions for running the Decoder locally will not work.

**Comment by jklukas** [comment]
See https://github.com/mozilla/gcp-ingestion/pull/1067
