### ISSUE TITLE
Error message from worker: java.io.UncheckedIOException: com.maxmind.db.InvalidDatabaseException: The MaxMind DB file's data section contains bad data: pointer larger than the database.

### ISSUE THREAD

**Issue by whd** [mozilla/gcp-ingestion#1059]
[Example failing stage job](https://console.cloud.google.com/dataflow/jobs/us-west1/2019-12-30_16_14_59-11135197587585267802?project=moz-fx-data-beam-nonprod-b5f4&organizationId=442341870013) and [stack trace](https://console.cloud.google.com/errors/CLKijszqiayVPg?time=P1D&project=moz-fx-data-beam-prod-11f7&organizationId=442341870013).

GeoIP DB: gs://moz-fx-data-prod-geoip/GeoIP2-City/20191231/GeoIP2-City.mmdb 

This appears to be the result of an actual GeoIP DB change, as when I reverted production to 20191224 the error stopped.

**Comment by jklukas** [comment]
I ran into a perhaps related error while running a backfill job to add geo info to payload_bytes_error:

```
 java.lang.RuntimeException: org.apache.beam.sdk.util.UserCodeException: java.io.UncheckedIOException: java.nio.charset.MalformedInputException: Input length = 1
```

I was using the latest DB: gs://moz-fx-data-prod-geoip/GeoIP2-City/20200204/GeoIP2-City.mmdb

Of note, I ran a sample job over just a single day of data and it completed successfully. This full backfill job looks like it still managed to process billions of messages successfully, so it's maybe a transient error? But I think the pipeline would have recovered if that were the case.

**Comment by jklukas** [comment]
This case could actually be a bad record. The line in our ingestion-beam code where this is happening is not when we load the DB, but rather while processing a response.

**Comment by jklukas** [comment]
Further digging into the stack trace shows that it's the call to `geoIP2.city` that throws the error. The MaxMind `CharsetDecoder#decodeLoop` method where the issue is thrown internally documents:

```
     * @throws  MalformedInputException
     *          If the byte sequence starting at the input buffer's current
     *          position is not legal for this charset and the current malformed-input action
     *          is {@link CodingErrorAction#REPORT}
```

Perhaps we should just catch this case?

**Comment by jklukas** [comment]
I moved ahead with the catching this case for the backfill of geo to the errors table. I added a counter for the malformed input and there were only 2 instances. The job finished successfully. I will file a PR to add the same changes to gcp-ingestion.

I think this ended up being unrelated to the error that @whd originally reported for this issue, so we'll keep it open.

**Comment by whd** [comment]
I'm going to close this as the latest version of geoip has been running in prod for a few days now without issues. We can reopen if it occurs again.
