### ISSUE TITLE
Report whether sink output is delayed due to input limits

### ISSUE THREAD

**Issue by relud** [mozilla/gcp-ingestion#1065]
In ingestion-sink if input limits are reached long before output batches are full then the sink will idle until batches time out, which could break autoscaling.

We should report metrics necessary to determine if this is happening.

If this is a problem we are hitting then we can adjust limits, but a more general fix would be to flush batches when input limits are reached via a custom Pub/Sub subscriber implementation.

**Comment by relud** [comment]
cc @whd this could be causing the current autoscaling issues, but it's hard to say without data, and the 1 second batch limit makes me feel like it's not likely.

**Comment by whd** [comment]
The current autoscaling issues are known to be because of https://bugzilla.mozilla.org/show_bug.cgi?id=1607349, but having pods with CPU idle even with significant backlog is potentially consistent with the earlier autoscaling issue I observed (before the metrics server broke).

**Comment by relud** [comment]
the subscriber SDK doesn't directly expose this information, but when debugging file loads the batch metrics added in #1240 were sufficient to identify this issue, so I'm going to consider this closed for now.
