### ISSUE TITLE
Document current stats on pipeline deduplication

### ISSUE THREAD

**Issue by jklukas** [mozilla/gcp-ingestion#1072]
As we respond to increased volume through structured ingestion, we are having capacity issues for our Redis-based in-pipeline deduplication.

We want to document how often the current deduplication is actually removing pings in structured ingestion, ideally per doctype, in order to better understand how much benefit we receive from in-pipeline deduplication.

**Comment by jklukas** [comment]
cc @whd @relud

**Comment by jklukas** [comment]
During the first week of this year, the only structured pings with > 1% dupe rate in the pipeline are mobile activation and fenix activation.

activity-stream and related high-volume pings are all below 0.1% duplicate rate in that period.

```
WITH err AS (
SELECT
  concat(replace(document_namespace, '-', '_'), '__', replace(document_type, '-', '_'), '_v', document_version) AS tbl,
  COUNT(*) AS n_err
FROM
  `moz-fx-data-shared-prod.payload_bytes_error.structured`
WHERE
  DATE(submission_timestamp) between "2020-01-01" and "2020-01-07"
  AND error_message = 'com.mozilla.telemetry.decoder.Deduplicate$DuplicateIdException: A message with this documentId has already been successfully processed.'
GROUP BY
  1
  ),
  raw AS (
  SELECT
  _table_suffix as tbl,
  COUNT(*) AS n
FROM
  `moz-fx-data-shared-prod.payload_bytes_decoded.structured_*`
WHERE 
  DATE(submission_timestamp) between "2020-01-01" and "2020-01-07"
group by 1
  )
select *, n_err/n AS ratio from raw left join err using (tbl) order by ratio desc
```


Row | tbl | ratio |  
-- | -- | -- | --
1 | mobile__activation_v1 | 0.014858067311538357 |  
2 | org_mozilla_fenix__activation_v1 | 0.011182346801848814 |  
3 | org_mozilla_fenix__metrics_v1 | 0.009746080796449213 |  
4 | org_mozilla_fenix_nightly__metrics_v1 | 0.008494997931017696 |  
5 | org_mozilla_fenix_nightly__baseline_v1 | 0.008194697701413282 |  
6 | org_mozilla_fenix__baseline_v1 | 0.008069226250579844 |  
7 | org_mozilla_fenix_nightly__events_v1 | 0.006485483200871925 |  
8 | org_mozilla_fenix__events_v1 | 0.00635439852301688 |  
9 | org_mozilla_fenix__bookmarks_sync_v1 | 0.003216946825013351 |  
10 | org_mozilla_fenix__history_sync_v1 | 0.00195583652602916 |  
11 | org_mozilla_tv_firefox__baseline_v1 | 0.001388914451002137 |  
12 | org_mozilla_vrbrowser__session_end_v1 | 9.846900923990017E-4 |  
13 | org_mozilla_vrbrowser__events_v1 | 9.526971433520505E-4 |  
14 | org_mozilla_vrbrowser__baseline_v1 | 7.522603978300181E-4 |  
15 | pocket__fire_tv_events_v1 | 6.863110898763921E-4 |  
16 | messaging_system__undesired_events_v1 | 6.138506438703931E-4 |  
17 | org_mozilla_vrbrowser__metrics_v1 | 4.611874362833147E-4 |  
18 | messaging_system__cfr_v1 | 3.763386822081437E-4 |  
19 | eng_workflow__build_v1 | 3.553502420823524E-4 |  
20 | messaging_system__onboarding_v1 | 2.318002556124637E-4 |  
21 | activity_stream__events_v1 | 1.9013625734441364E-4 |  
22 | messaging_system__snippets_v1 | 1.4387611834481754E-4 |  
23 | firefox_installer__install_v1 | 7.597306596025558E-5 |  
24 | activity_stream__spoc_fills_v1 | 7.359820514610591E-5 |  
25 | activity_stream__impression_stats_v1 | 6.865454439539442E-5 |  
26 | firefox_launcher_process__launcher_process_failure_v1 | 3.4150455789455294E-5

**Comment by jklukas** [comment]
Note that we have now turned off streaming deduplication for the `structured` pipeline family. We are still deduping for `telemetry` which has a much lower overall _number_ of pings.

Considering that we have full deduplication applied for `stable` tables, streaming deduplication may not be necessary for `telemetry` anymore. We could consider implementing a lower quality of service deduplication that doesn't require Redis or any other external data store, which would be a nice cost savings and operational simplification.

For `telemetry`, we should investigate overall dupe rates and look at dupe rates per client_id to better understand the situation.

**Comment by jklukas** [comment]
## Dupe ratios for telemetry

During the period 2020-04-01 through 2020-04-07, here are the dupe ratios for telemetry  doctypes (we ignore tables with fewer than 1000 dupes):



Row | tbl | ratio |  
-- | -- | -- | --
1 | telemetry__deletion_v4 | 0.31867335683543485 |  
2 | telemetry__deployment_checker_v4 | 0.11312007417709782 |  
3 | telemetry__shield_study_v4 | 0.05793491361992768 |  
4 | telemetry__new_profile_v4 | 0.0349170692750579 |  
5 | telemetry__saved_session_v4 | 0.03375634097615193 |  
6 | telemetry__health_v4 | 0.03302159328539881 |  
7 | telemetry__pre_account_v4 | 0.027985324442302027 |  
8 | telemetry__heartbeat_v4 | 0.0229335004495903 |  
9 | telemetry__first_shutdown_v4 | 0.02222672920476398 |  
10 | telemetry__core_v9 | 0.014422207094347486 |  
11 | telemetry__core_v8 | 0.011495446136110792 |  
12 | telemetry__main_v4 | 0.009057948813360417 |  
13 | telemetry__core_v10 | 0.008278297885462471 |  
14 | telemetry__crash_v4 | 0.0080450530480156 |  
15 | telemetry__focus_event_v1 | 0.007873070318422576 |  
16 | telemetry__core_v7 | 0.005562876660310659 |  
17 | telemetry__third_party_modules_v4 | 0.005091548439943876 |  
18 | telemetry__mobile_metrics_v1 | 0.004939849030618256 |  
19 | telemetry__mobile_event_v1 | 0.004731014924366198 |  
20 | telemetry__downgrade_v4 | 0.004708531336302341 |  
21 | telemetry__event_v4 | 0.004415322546360771 |  
22 | telemetry__modules_v4 | 0.0039266807621652685 |  
23 | telemetry__update_v4 | 0.0032746865295374813 |  
24 | telemetry__sync_v4 | 0.0021975328800266413 |  
25 | telemetry__bhr_v4 | 0.0020734195132399535

**Comment by jklukas** [comment]
Again, let's consider the week from 2020-04-01 through 2020-04-07. Model query for this section:

```
WITH by_id AS (
SELECT
  client_id,
  count(*) n_occurrences
FROM
  `moz-fx-data-shared-prod.payload_bytes_error.telemetry`
WHERE
  DATE(submission_timestamp) between "2020-04-01" and "2020-04-07"
  AND error_message = 'com.mozilla.telemetry.decoder.Deduplicate$DuplicateIdException: A message with this documentId has already been successfully processed.'
  AND document_type = 'main'
GROUP BY
  1)
  select n_occurrences, count(*) as frequency from by_id
group by 1
order by 1 desc
```

## Number of dupes per document_id

Focusing on main pings, we see 10 individual document_id values that are duplicated more than 100k times in the week. We see 65 that occur more than 10k times. We see 387 that appear more than 1k times.

## Number of pings per client_id

Focusing on main pings, we see 1 client_id that generated over 1M pings. 10 generated over 100k pings each. 58 generated over 10k pings each. 809 generated over 1k pings each.

**Comment by whd** [comment]
For this analysis 2020-04-01 through 2020-04-07 is a good time frame as there were no known issues with dedup (this week  and particularly 2020-04-29 is not a good time frame because we had a [redis failure](https://github.com/mozilla-services/cloudops-infra/pull/2094) that required a cutover).

**Comment by jklukas** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1627758 for capturing the task of deciding on turning off deduplication.

**Comment by jklukas** [comment]
We have turned off Redis-based dedupe, and now rely on Dataflow-based dedupe that we are not able to monitor stats on.
