### ISSUE TITLE
Limit the Pocket republished stream to a single doctype

### ISSUE THREAD

**Issue by jklukas** [mozilla/gcp-ingestion#1082]
I got pinged by @ncloudioj earlier today about a question from Pocket. They've been seeing cost go up for processing the Pub/Sub topic that we republish into their project. It turns out they only care about the `impression-stats` doctype, but their topic is receiving all pings for the `activity-stream` namespace; the items they care about are only about 20% of what we're publishing.

I had initially thought we could just change configuration and publish to the existing topic, but had forgotten that only our per-namepace republishing option allows specifying a full topic path. 

For the time being, we can change to use the existing per-doctype configuration options, but we have to set `--perDocTypeDestination` to be exactly the path to the existing Pocket stream rather than a pattern. We can only do this because the structured republisher currently doesn't have any per-doctype destinations configured; if we find another docType we want to republish from there, we'd be stuck.

Longer-term, we should probably add a new `--perDocTypesDestination` option that would accept a map of topic names to lists of desired doctypes. We should probably deprecate the existing per-doctype option in favor of this; it's more verbose, but more flexible.

cc @relud @whd

**Comment by jklukas** [comment]
The short-term change has been deployed, so we are now publishing only `impression-stats` to the pocket topic.

**Comment by jklukas** [comment]
I think the right long-term design is to introduce a param called `--perDocTypeDestinations` which is parallel to `--perNamespaceDestinations`. The new param would be of type `Map<String, List<String>>` and would be passed in as json (Beam handles parsing json params into the declared types of params).

So our use of the option would become:

```
--perDocTypeDestination='{"pocket-topic-name":["activity-stream/impression-stats"]}'
``` 

Once we implement this option and deploy it, we can transition all existing uses of the old `perDocTypeDestination` param to the new one, then remove the old param from the code completely.

**Comment by jklukas** [comment]
Reopening this since we have not yet actually updated the configuration to use the new option. We can close this once all uses of the deprecated option are gone and the underlying code is removed.

**Comment by whd** [comment]
Configuration has been updated ([e.g.](https://console.cloud.google.com/dataflow/jobs/us-west1/2020-03-31_17_40_37-2856634058451422227?project=moz-fx-data-beam-prod-11f7&organizationId=442341870013)) so removal of deprecated options can probably commence.
