### ISSUE TITLE
Perform GeoIP lookup first in Decoder

### ISSUE THREAD

**Issue by jklukas** [mozilla/gcp-ingestion#1096]
We would like to remove the `ip` field from payload_bytes_error. To do this, we need to make sure that we always have performed GeoIP lookup before a record is marked invalid and sent to error output.

We need to make geo the first transform in the Decoder and ensure that any exceptions in that transform bubble up to shut down the worker rather than going to error output.

cc @whd @relud

**Comment by relud** [comment]
> We would like to remove the `uri` field from payload_bytes_error.

you mean `ip`?

**Comment by jklukas** [comment]
Note that currently our input transform allow catching of errors and sending to error output, but in practice we never hit these error cases.

For all data from 2020:

```
SELECT
  error_type,
  COUNT(*)
FROM
  `moz-fx-data-shared-prod.payload_bytes_error.telemetry`
WHERE
  DATE(submission_timestamp ) >= '2020-01-01'
GROUP BY
  1
ORDER BY
  2 DESC
```

This is the result:

Row | error_type | f0_ |  
-- | -- | -- | --
1 | ParsePayload | 292009518 |  
2 | Duplicate | 262640495 |  
3 | ParseUri | 2432337 |  
4 | Deduplicate.RemoveDuplicates | 16602 |  
5 | LimitPayloadSize | 257

So no messages are going to error output from the input phase.

I think this means we can safely change the inputs to not support errors. Instead, if they raise an exception, it will bubble up and stop the pipeline.

In practice, I think the only input that _could_ throw an exception is the text-based `json` inputType. We only use that in tests and not in production.

**Comment by jklukas** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1613225 for further steps needed to complete this migration.
