### ISSUE TITLE
Drop fixed clientid c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0 in decoder

### ISSUE THREAD

**Issue by whd** [mozilla/gcp-ingestion#1125]
https://bugzilla.mozilla.org/show_bug.cgi?id=1489560#c5

It sounds like we want to keep these in the errors table instead of dropping them completely. Another option mentioned would be to shred these with shredder instead of handling them explicitly.

**Comment by scholtzan** [comment]
Fixed in https://github.com/mozilla/gcp-ingestion/pull/1127
