### ISSUE TITLE
Design for supporting FxA event streaming to Amplitude

### ISSUE THREAD

**Issue by jklukas** [mozilla/gcp-ingestion#1137]
We've identified "Amplitude streaming server metrics" as the first part of the FxA pipeline migration to pursue. This issue discusses what needs to be implemented on the data pipeline side to support this.

## Basic flow of data

- FxA publishes "amplitudeEvent"-type messages to a PubSub topic
  - Some basic filtering based on auth codes is applied before publishing to get the data to a reasonable volume
- A new instance of the Decoder job consumes from the new topic
  - We pretty much only care about the schema validation and error routing features here; would need a BQ sink for the error topic, but not for the raw or decoded data
- The decoded topic is used as input to a new Dataflow job that handles sending messages to Amplitude

## Differences from previous discussions

@jbuck and @whd had discussed keeping the existing FxA-side JS job for sending data to Amplitude. But in that discussion, we had missed the fact that we want to send this data through the Decoder to get full schema validation and error handling, which are currently missing and a risk for FxA.

## Additional risk: HMACing of IDs

The existing FxA data pipeline HMACs the user IDs before sending to Amplitude. We need to use the same technique in order to provide continuity in the FxA data. I am also working under the assumption that we want to be sure that raw FxA IDs never hit BigQuery in `shared-prod`.

That means that IDs need to be HMAC'd either on the FxA side before they're sent to Pub/Sub, or that we need to run the HMAC as part of the Decoder. It seems lower effort to keep this on the FxA side, so I'd like it to happen there if possible.

## Action items

In order to make this happen, we need the following at a minimum:

- Define a schema for these fxa amplitude events in mozilla-pipeline-schemas
- Provision a Pub/Sub topic; should this be FxA-side or data platform side?
- Implement an Amplitude sink Dataflow job

**Comment by whd** [comment]
>     * Provision a Pub/Sub topic; should this be FxA-side or data platform side?

I'm presently of the opinion this should live data-platform side, with write access granted to fxa service accounts. This is not a strongly held opinion.

**Comment by jklukas** [comment]
Starting to track work under a metabug: https://bugzilla.mozilla.org/show_bug.cgi?id=1617712

**Comment by jklukas** [comment]
No longer relevant as we are discontinuing use of Amplitude.
