### ISSUE TITLE
beam live sink error: com.mozilla.telemetry.ingestion.core.util.BubbleUpException

### ISSUE THREAD

**Issue by whd** [mozilla/gcp-ingestion#1199]
Offshoot of https://github.com/mozilla/gcp-ingestion/issues/667, discovered while investigating https://bugzilla.mozilla.org/show_bug.cgi?id=1622977.

Example error file in GCS: gs://moz-fx-data-prod-data/telemetry-decoded_bq-sink/error/2020-03-11/14/error-2020-03-11T14-40-00.000Z-2020-03-11T14-50-00.000Z-0-00059-of-00060.ndjson.gz

Sample of relevant error fields:

    {
        "stack_trace_cause_2": "[java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184), java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392), java.net.Socket.connect(Socket.java:589), sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673), sun.net.NetworkClient.doConnect(NetworkClient.java:175), sun.net.www.http.HttpClient.openServer(HttpClient.java:463), sun.net.www.http.HttpClient.openServer(HttpClient.java:558), sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264), sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367), sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191), sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156), sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050), sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177), sun.net.www.protocol.https.HttpsURLConnectionImp...",
        "stack_trace_cause_1": "[com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.translate(HttpBigQueryRpc.java:100), com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.getDataset(HttpBigQueryRpc.java:112), com.google.cloud.bigquery.BigQueryImpl$5.call(BigQueryImpl.java:289), com.google.cloud.bigquery.BigQueryImpl$5.call(BigQueryImpl.java:286), com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105), com.google.cloud.RetryHelper.run(RetryHelper.java:76), com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50), com.google.cloud.bigquery.BigQueryImpl.getDataset(BigQueryImpl.java:285), com.google.cloud.bigquery.BigQueryImpl.getDataset(BigQueryImpl.java:276), com.mozilla.telemetry.transforms.KeyByBigQueryTableDestination.lambda$getTableDestination$2(KeyByBigQueryTableDestination.java:103), com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4876), com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529), com.google.common.cache.LocalCache$Segme...",
        "error_type": "KeyByBigQueryTableDestination",
        "error_message": "com.mozilla.telemetry.ingestion.core.util.BubbleUpException: com.google.cloud.bigquery.BigQueryException: www.googleapis.com",
        "stack_trace": "[com.mozilla.telemetry.transforms.KeyByBigQueryTableDestination.getTableDestination(KeyByBigQueryTableDestination.java:112), com.mozilla.telemetry.transforms.KeyByBigQueryTableDestination.lambda$expand$3c5ff6eb$1(KeyByBigQueryTableDestination.java:134), org.apache.beam.sdk.transforms.Contextful.lambda$fn$36334a93$1(Contextful.java:112), org.apache.beam.sdk.transforms.MapElements$MapWithFailures$MapFn.processElement(MapElements.java:324), org.apache.beam.sdk.transforms.MapElements$MapWithFailures$MapFn$DoFnInvoker.invokeProcessElement(Unknown Source), org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:222), org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.processElement(SimpleDoFnRunner.java:183), org.apache.beam.runners.dataflow.worker.SimpleParDoFn.processElement(SimpleParDoFn.java:335), org.apache.beam.runners.dataflow.worker.util.common.worker.ParDoOperation.process(Pa..."
    }

**Comment by jklukas** [comment]
The intention of BubbleUpException was that we always make that exception type bring the whole worker down rather than going to error output. But we should have removed this while refactoring error handling to use facilities now built in to the Beam API. I missed that completely in reviews.

To prevent this problem in the future, we need to remove all uses of BubbleUpException and make sure that every use of `exceptionsVia` rethrows the exception and catches only the specific exceptions we expect and want to route to error output.

**Comment by jklukas** [comment]
cc @scholtzan Would you be able to pick this up?
