### ISSUE TITLE
decoder does ParseUri step after ValidateSchema step

### ISSUE THREAD

**Issue by relud** [mozilla/gcp-ingestion#139]
but output of ParseUri is needed to determine schema to validate

**Comment by jklukas** [comment]
Looks like we're already doing this in the correct order: https://github.com/mozilla/gcp-ingestion/blob/master/ingestion-beam/src/main/java/com/mozilla/telemetry/Decoder.java#L48-L51

Is this good to close, or have I simply misunderstood the problem?

**Comment by relud** [comment]
huh, looks like i misread the ordering.
