### ISSUE TITLE
Optionally discard geo_city based on presence in a city size file

### ISSUE THREAD

**Issue by relud** [mozilla/gcp-ingestion#144]
https://github.com/mozilla-services/lua_sandbox_extensions/blob/master/moz_ingest/io_modules/decoders/moz_ingest/common.lua#L26-L28

**Comment by jklukas** [comment]
Note @whd's thoughts in https://github.com/mozilla/gcp-ingestion/issues/145#issuecomment-434023327 that this city database has not been something we are actively updating. Should we still build in support?
