### ISSUE TITLE
Allow periodic reloading of external resources

### ISSUE THREAD

**Issue by jklukas** [mozilla/gcp-ingestion#145]
We are beginning to reference a number of external resources in our Beam job. Current and planned resources to reference are:

- MaxMind GeoCity database (stored in GCS)
- City size filter file (likely to be stored in GCS)
- Pipeline schemas (currently copied in at build time from GitHub, but could also live in GCS)

All of the above currently are loaded once at either build or pipeline startup time. We already know that we want to support updating schemas without draining the job. If we understand at this point that we'll want to be able to run a single job for weeks or months at a time without restarting, we should likely establish an expectation that we are able to dynamically reload resources.

In particular, it looks worthwhile at this point to build generic support for monitoring files on GCS and reloading when new content is detected. This may take the form of a configurable `PTransform`.

cc @relud for thoughts here

**Comment by jklukas** [comment]
This is not quite as straight-forward as I initially thought. We are currently using Beam's `FileSystem` API to resolve the `geoCityDatabase` path and support both local and GCS locations. This API unfortunately does not give any access to modification timestamps, so any polling we do would have to access the full file every time rather than just checking if it's been updated.

We could make a PR to upstream Beam to add timestamp metadata, which I don't think would be a large effort, but could take some time to get through design discussion and review.

If we want to implement this in the shorter term, we either need to blindly pull the resource and update on some schedule, or we need to write our own code to parse `gs://` paths vs. local paths and have separate code to fetch each.

**Comment by relud** [comment]
@whd can you add some information here regarding how often we expect to update the geoip2 and city size databases?

My expectation for those inputs is that they are read once, and that operations will issue an `update` operation to the job when it changes. This requires testing that issuing an `update` without changing the dataflow template or arguments will cause the transforms to be reloaded. If testing proves this to be simple enough, it may also be the preferable way to handle `mozilla-pipeline-schemas` updates.

Unlike handling updates live, this has the downside that we can't necessarily fall back to the cached content if we hit an exception loading the resource (such as insufficient permissions, invalid json, etc).

**Comment by jklukas** [comment]
According to [MaxMind docs](https://support.maxmind.com/geoip-faq/geoip2-and-geoip-legacy-databases/how-often-are-the-geoip2-and-geoip-legacy-databases-updated/), a new update to the GeoIP2 database is available every Tuesday. @whd may be able to comment on whether we want to immediately take all those updates.

> My expectation for those inputs is that they are read once, and that operations will issue an update operation to the job when it changes

I will read up on Dataflow updates

**Comment by whd** [comment]
> According to MaxMind docs, a new update to the GeoIP2 database is available every Tuesday. @whd may be able to comment on whether we want to immediately take all those updates.

Weekly is correct. The data infrastructure applies them within an hour of them being made available by the upstream jenkins job. I would expect to do the same in the gcp infra since this has never caused issues.

>  city size databases

The use of this database was kind of hacked together last minute and has mostly been forgotten. We don't pay for it and we don't update it. We might want to revisit those things from a policy perspective, but from an infrastructure perspective updating them should work the same way as the geoip database.

> My expectation for those inputs is that they are read once, and that operations will issue an update operation to the job when it changes.

This was my expectation as well.

> Unlike handling updates live, this has the downside that we can't necessarily fall back to the cached content if we hit an exception loading the resource (such as insufficient permissions, invalid json, etc).

This seems vaguely worrisome, relative to the current infra where we will simply continue to use the existing db. I don't think it's a big enough issue to actively work around it (I haven't been following this issue) but if it works that way, then great.

**Comment by relud** [comment]
> the current infra [...] will simply continue to use the existing db

I think that issuing an update operation will blow the in-memory cache, so in order to "continue to use the existing db" we would need to cache it somewhere else, which we don't yet do.

**Comment by jklukas** [comment]
Reading up on https://cloud.google.com/dataflow/pipelines/updating-a-pipeline, the Dataflow update operation spins up an entirely new job with a new `jobId`, so I think we can safely assume that all the same startup code runs and we'd be fetching resources from GCS again (if they're fetched as a result of class construction, which is the case so far here).

> we can't necessarily fall back to the cached content if we hit an exception loading the resource

As long as we're standardizing on having these resources live in GCS, this seems reasonable to me. If GCS as a whole service is having issues, we can't expect to make real progress anyway, and if we have permissions or content issues, I'd want us to know about that quickly.

Perhaps an ideal situation is if Dataflow's update step backs out in the case that there's an error on startup of the new pipeline. If we can make sure we fetch all external resources at construction time and not pipeline execution time, then this might work quite well.

**Comment by relud** [comment]
> If we can make sure we fetch all external resources at construction time and not pipeline execution time, then this might work quite well.

IIUC we fetch can only fetch ValueProvider content at execution time, and the alternative is to have this content baked into the Dataflow template.

**Comment by jklukas** [comment]
> IIUC we can only fetch ValueProvider content at execution time

You're right; I forgot about that wrinkle.

For the time being, it sounds like we're fine with the general strategy of having to issue a Dataflow `update` to reload resources, and that will be happening at least once a week to update the geoCity database.

Perhaps we can consider building validation of external resources into our testing flow. Before we redeploy the production Dataflow job, we make sure the dev job has been redeployed with the latest resources and is passing integration tests. That would give us some protection against permissions and encoding bugs.
