### ISSUE TITLE
Choose variable entry from X-Forwarded-For in GeoCityLookup

### ISSUE THREAD

**Issue by relud** [mozilla/gcp-ingestion#160]
currently we look at the oldest entry in the `X-Forwarded-For` header, but the aws pipeline looks at the one right before the ELB.

In order to handle traffic duplicated from the aws pipeline we need to handle choosing different items from the list based on whether or not the request is from the aws pipeline client.

after discussion with @whd, decided we should set a header on the aws pipeline client when forwarding requests to gcp ingestion, configure the header as part of #13, and when the attribute for that header is present the decoder should choose a different entry from `X-Forwarded-For` to use for GeoIP lookups.

I am arbitrarily naming the header that controls this behavior `X-Pipeline-Proxy`. How to properly configure the header will be determined during implementation, in case allowances need to be made for suboptimal behavior.

**Comment by jklukas** [comment]
Fixed by #165
