### ISSUE TITLE
Remove AET tests in ingestion-beam

### ISSUE THREAD

**Issue by relud** [mozilla/gcp-ingestion#1620]
they are failing due to missing schemas, e.g. https://app.circleci.com/pipelines/github/mozilla/gcp-ingestion/2092/workflows/9f21fff8-ebb4-493f-abae-046c96d8b089/jobs/38999

**Comment by whd** [comment]
I'm rolling out the AET decomm now and https://github.com/mozilla/gcp-ingestion/pull/1599 should handle this.

**Comment by whd** [comment]
You're probably good once you rebase.
