### ISSUE TITLE
Error message from worker: java.lang.NullPointerException com.mozilla.telemetry.decoder.rally.DecryptRallyPayloads$Fn.apply(DecryptRallyPayloads.java:188) 

### ISSUE THREAD

**Issue by whd** [mozilla/gcp-ingestion#1670]
/CC @Dexterp37

```
2021-04-29 08:52:02.703 GMT
Error message from worker: java.lang.NullPointerException com.mozilla.telemetry.decoder.rally.DecryptRallyPayloads$Fn.apply(DecryptRallyPayloads.java:188) com.mozilla.telemetry.decoder.rally.DecryptRallyPayloads$Fn.apply(DecryptRallyPayloads.java:114) org.apache.beam.sdk.transforms.Contextful.lambda$fn$36334a93$1(Contextful.java:112) org.apache.beam.sdk.transforms.FlatMapElements$FlatMapWithFailures$MapFn.processElement(FlatMapElements.java:344) java.lang.NullPointerException com.mozilla.telemetry.decoder.rally.DecryptRallyPayloads$Fn.apply(DecryptRallyPayloads.java:188) com.mozilla.telemetry.decoder.rally.DecryptRallyPayloads$Fn.apply(DecryptRallyPayloads.java:114) org.apache.beam.sdk.transforms.Contextful.lambda$fn$36334a93$1(Contextful.java:112) org.apache.beam.sdk.transforms.FlatMapElements$FlatMapWithFailures$MapFn.processElement(FlatMapElements.java:344)
```

https://github.com/mozilla/gcp-ingestion/blob/main/ingestion-beam/src/main/java/com/mozilla/telemetry/decoder/rally/DecryptRallyPayloads.java#L188

This is throwing a `NullPointerException` which definitely isn't correct, but it looks like it was just going to throw a slightly more descriptive error anyway. AFAICT this is a code or schemas issue (or both). Certainly input data shouldn't be able to render the decoder unresponsive.

**Comment by whd** [comment]
It appears from slack that @Dexterp37 is trying to add glean to `rally-zero-one`, which could possibly explain the issue. I doubt we are going to be able to retrofit glean processing onto that given the schema issues we're seeing here. Minimally a schemas change would need to be made to that study but I think we should avoid doing that.

**Comment by Dexterp37** [comment]
> 
> 
> It appears from slack that @Dexterp37 is trying to add glean to `rally-zero-one`, which could possibly explain the issue. I doubt we are going to be able to retrofit glean processing onto that given the schema issues we're seeing here. Minimally a schemas change would need to be made to that study but I think we should avoid doing that.
> 
> If I'm right here, this means we should send these glean pings to the errors stream instead of hard-failing.

Yes, I indeed sent a ping there (by mistake). I was not really expecting things to fail so hard :O

Does this mean that anyone that has the public key could send a maliciously crafted ping to the decoder to break it?

**Comment by jklukas** [comment]
> This is throwing a NullPointerException which definitely isn't correct, but it looks like it was just going to throw a slightly more descriptive error anyway.

It would have thrown `DecryptRallyPayloadsException` which is caught and sent to error output: https://github.com/mozilla/gcp-ingestion/blob/main/ingestion-beam/src/main/java/com/mozilla/telemetry/decoder/rally/DecryptRallyPayloads.java#L95

So if we fix the NPE problem, future occurrences of this shouldn't take down the pipeline.
