### ISSUE TITLE
Decoder GCS -> GCS integration test

### ISSUE THREAD

**Issue by jklukas** [mozilla/gcp-ingestion#210]
We should:

- produce a non-trivial input file on GCS with raw ping inputs
- produce the expected output file on GCS
- write a test that validates expected and actual outputs match

**Comment by jklukas** [comment]
I don't at the moment have a good strategy for creating the input dataset here. Could start from @acmiyaguchi's sampled production data, but it might be quite a project to convert those files to the PubsubMessage-formatted json we'd need to put in GCS as input.

If we are currently running ingestion-edge in dev and have data we've pushed through it and saved to GCS, that would be the most convenient input. I'll check with data ops on that.

**Comment by relud** [comment]
This is a bit more than what I had in mind. I was thinking of something that combined all the steps from the existing transform unit tests into a single input file, and checked the output and error output. Not something so large as sampling real inputs.

**Comment by jklukas** [comment]
Sounds similar to #209, so perhaps we can have one test that operates on local files and an integration test that copies those local files to GCS and runs the same logic, but accessing the resources in GCS.
