### ISSUE TITLE
Appending "metadata" field could result in invalid JSON

### ISSUE THREAD

**Issue by mreid-moz** [mozilla/gcp-ingestion#279]
In the [`AddMetadata`](https://github.com/mozilla/gcp-ingestion/blob/master/ingestion-beam/src/main/java/com/mozilla/telemetry/decoder/AddMetadata.java#L31) decoder, we insert a top-level `"metadata"` field in the JSON representation. If the payload itself already includes a `"metadata"` field we could end up with a duplicate key. 

Do we enforce that `"metadata"` is not allowed at the top level of incoming submissions? 

This could be handled at the schema level or in this codebase (or both).

**Comment by jklukas** [comment]
I'm going to modify our `ParsePayload` transform to remove any existing "metadata" field and parse it into attributes. This will have the secondary benefit of allowing us to have more flexibility in recovering files that have been saved in "text" format with metadata already in the payload.
