### ISSUE TITLE
Plumb "core" pings output to BigQuery

### ISSUE THREAD

**Issue by mreid-moz** [mozilla/gcp-ingestion#280]
While we finalize the generalized plan for handling [all pings being written to BigQuery](https://docs.google.com/document/d/1oPp_J4AoB3llgAe5Gp1SVPtkA2xUjZR5TKL0CVOZKx8/edit#) it would be useful to implement a simpler BigQuery output to prove out the end-to-end ingestion<-->BQ pipeline.

The `core` ping seems like a good candidate here due to its simple and relatively stable structure, and medium-sized submission volume.

We'll need to create a BigQuery schema from a combination of the [incoming schema](https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/dev/schemas/telemetry/core/core.9.schema.json) and the `metadata` structure, then set up a corresponding [Dataflow job](https://github.com/mozilla/gcp-ingestion/tree/master/ingestion-beam#sink-job) to process the core pings in PubSub.

**Comment by jklukas** [comment]
This schema contains one field ("searches") of map type. We can't represent that using the machinery we currently have, but I'm going to move forward for now simply omitting that field from the BQ schema.

**Comment by jklukas** [comment]
Adding the following manually to the schema to accomodate metadata:

```
    {
      "fields": [
        {
          "type": "STRING", 
          "mode": "REQUIRED", 
          "name": "document_id"
        }, 
        {
          "type": "TIMESTAMP", 
          "mode": "REQUIRED", 
          "name": "submission_timestamp",
            "description": "Time when the ingestion edge server accepted this message"
        }, 
        {
          "type": "STRING", 
          "mode": "NULLABLE", 
          "name": "geo_country"
        },
        {
          "type": "STRING", 
          "mode": "NULLABLE", 
          "name": "geo_city"
        }
      ],
      "type": "RECORD", 
      "mode": "REQUIRED", 
      "name": "metadata"
    }, 
```

And ran:

```
bq mk --table \
  --description="Core ping; see https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/dev/templates/telemetry/core/core.9.schema.json" \
  --schema core.bq.schema.json \
  moz-fx-data-shar-nonprod-efed:telemetry_dev.core_v9
```

It is not yet getting populated due to upstream pipeline issues, but the table now exists.

**Comment by jklukas** [comment]
Need a new schema: https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/243

**Comment by jklukas** [comment]
Calling this done for now. The work that @acmiyaguchi is doing to investigate Avro support, etc. will likely address the map type problem for core pings.
