### ISSUE TITLE
Compression strategy

### ISSUE THREAD

**Issue by jklukas** [mozilla/gcp-ingestion#324]
We have observed a Decoder failure with a message too large to publish to Pubsub. This is likely due to the payload being gzipped when sent to the edge, and then the Decoder is unzipping the content and publishing the unzipped payload, which is substantially larger than the original message.

Firefox should never send a payload larger than 10 MB, and the existing AWS edge should be unzipping and rejecting any payload larger than 10 MB uncompressed, but the error we saw actually complained about a 7 MB payload. Pubsub requires a base64 encoded payload, which ends up being 4 bytes per 3 bytes of input, so the limit for an uncompressed and unencoded payload to Pubsub is actually 7 MB rather than 10 MB.

I need to look into whether the Pubsub service and clients have any built-in support for compression, or whether we should be handling this ourselves.

**Comment by jklukas** [comment]
> The edge does not unzip and does not limit based on uncompressed size.

This is talking about ingestion-edge in this repo, yes?

> The decoder should probably recompress the payload before sending it back to pubsub, because of the impact on pubsub pricing.

I agree. We need to do some investigation of compression formats and whether there's a clear case for using some format other than gzip, such as zstd.

> The base64 encoding issue can be worked around by sending messages to pubsub via GRPC instead of REST.

That makes sense. I fear that the Beam PubsubIO implementation is REST-based, though. I am going to start a Beam email thread about it.

**Comment by relud** [comment]
> This is talking about ingestion-edge in this repo, yes?

yes, but I definitely think it applies to both.

> That makes sense. I fear that the Beam PubsubIO implementation is REST-based, though. I am going to start a Beam email thread about it.

Well, we're gonna end up rewriting all the IO connectors anyway, might as well start with PubSub v_v

**Comment by jklukas** [comment]
Beam does contain a PubsubGrpcClient, but there does not appear to be a public interface to use it. Following up on beam lists.

@whd has mentioned zstd as being a better alternative to gzip for our uses. There are python and Java libraries for encoding/decoding, so using it could be feasible. Gzip support is provided in the standard library for both python and Java, so zstd definitely has the downside of requiring an additional dependency. I also expect we'd run into some issues with frameworks where gzip compression is well supported, but zstd would require some acrobatics.

**Comment by jklukas** [comment]
I've split off discussion of zstd vs. gzip to https://github.com/mozilla/gcp-ingestion/issues/325

For the purposes of this issue, I think I'm convinced that cost savings are a sufficient reason to:

1. Have ingestion-edge compress payloads before publishing to PubSub, and
2. Have ingestion-beam recompress parsed payloads before publishing back to PubSub

**Comment by whd** [comment]
For reference in the AWS pipeline the end-to-end compression is accomplished with https://cwiki.apache.org/confluence/display/KAFKA/Compression , for which pubsub does not appear to have an analogous concept (though I haven't checked for one). Kafka's end-to-end compression didn't support zstandard at the time (it's apparently happening in https://cwiki.apache.org/confluence/display/KAFKA/KIP-110%3A+Add+Codec+for+ZStandard+Compression), so we are using snappy. Regardless it appears we're going to have to make this application-level compression in GCP.

**Comment by jklukas** [comment]
I haven't been able to find any documentation about end-to-end compression for Pub/Sub, so I think it's safe to assume there's no analogous concept. We are looking at per-payload encryption for the publishing service and per-payload decryption for the subscribing service.

**Comment by jklukas** [comment]
## Proposed changes

For the time being, let's standardize on gzip and compress outputs by default. This will involve the following changes:

* Add a `--decompressInputMessages` boolean flag that defaults to true; we can set this to false if we have some case where we definitely don't want to try decompressing
* Move `GzipDecompress` directly into `InputType.pubsub.read` so it will always be applied to pubsub inputs (currently only applied in Decoder)
* Add a `--compressOutput` boolean flag that defaults to true
* Introduce a `GzipCompress` transform and add it to `OutputType.pubsub.write`  as long as `--compressOutput=true`
* Alter `OutputType.file` to set gzip compression (at the file level rather than at the message payload level) if `--compressOutput=true`

FileIO already automatically supports reading gzip compressed files (if file names end with `.gz`).

Then evaluation of zstd or other compression formats would remain as a future improvement. We could alter out `GzipDecompress` transform to be `DecompressMessages` and to handle the case of both gzip and zstd inputs.
