### ISSUE TITLE
Convert Sink from Scala to Java and document why

### ISSUE THREAD

**Issue by relud** [mozilla/gcp-ingestion#33]
Also documentation about why we are choosing java over scala, what it brings us, and some comparisons.

**Comment by relud** [comment]
fixed

**Comment by mreid-moz** [comment]
IIRC, choosing Java has the primary benefit of matching up with the documentation and example code for Beam. I think this issue is sufficient for describing "why", and we did end up revisiting the issue and supporting the initial decision to go with Java.
