### ISSUE TITLE
Don't strip attributes other than IP

### ISSUE THREAD

**Issue by jklukas** [mozilla/gcp-ingestion#359]
Per discussion with @whd and @relud, we want to retain all original attributes from the edge when writing out error messages, so that errors can be run right back through the pipeline.

Currently, we know we strip URI. We should restore that and look for others.

@relud suggests that we should at the same time, though, modify `AddMetadata` to inject only a known subset of potential attributes into the payload itself.

**Comment by jklukas** [comment]
@relud - Do you know if the current AWS pipeline has a filter for metadata attributes? Could we reuse that list?

**Comment by relud** [comment]
we should output these attributes in metadata: https://github.com/mozilla/gcp-ingestion/blob/master/docs/decoder.md#decoded-message-metadata-schema

**Comment by relud** [comment]
after further discussion in slack, i think we should not limit what we include in `AddMetadata`, instead allowing bigquery to strip fields not present in the schema.
