### ISSUE TITLE
Evaluate if beam is the right solution for decoder and sink services

### ISSUE THREAD

**Issue by relud** [mozilla/gcp-ingestion#371]
Known problems in beam:

- file output will ack messages in pubsub before delivery
- file output requires complex windowing logic
- file output does not support avro encoding (must use specific avro file output)
- pubsub input does not support reading from multiple topics
- pubsub output does not support writing to multiple topics
- pubsub output does not return a pcollection of messages delivered
- pubsub output uses rest api, which has a lower payload size limit
- bigquery output can crash pipeline on missing tables
- bigquery output transcodes from json to json, which wastes cpu
- bigquery streaming output does not preserve original message on exceptions
- bigquery batch output does not preserve files in gcs for reuse
- bigquery output requires cpu-expensive map transcoding, because json does not differentiate between maps and structs.

Known benefits of beam:

- great operational visibility through a UI that groups together logging, message throughput, metrics, and error rates
- managed service reduces operations effort
- has first-party support for autoscaling on pubsub topic volume
- leverages a standard library and its community
- has many pluggable input and output connectors
- file input orchestrates consumption of gcs files across workers

Possible benefits of a kubernetes service solution:

- can fix all of `Known problems in beam`
- fine-grained control of behavior
- fewer surprise caviats due to unexpected library behavior and limitations
- uses operations' standard deployment environment
- can be written in rust to push forward a mozilla language
- direct control of code allows for thorough speed optimization
- can potentially handle writing to multiple simultaneous dynamically named outputs (gcs (json, avro, and raw), bigquery (streaming and batch), multiple pubsub topics), saving significantly on pubsub cost.
- potentially easier to test outage scenarios in a prod-like environment

Possible problems in a kubernetes service solution:

- may require greater operations effort
- may require a custom solution for autoscaling
- does not have a clear solution for orchestrating consumption of gcs files across workers
- requires developer time to write all pieces from scratch, and would not have community provided input and output plugins

Possible benefits of writing custom IO plugins to fix `Known problems in beam`

- May contribute solutions upstream and improve beam for the community
- May keep most of our existing beam code
- May require less effort than kube solution

Possible problems in writing custom IO plugins to fix `Known problems in beam`

- May not be able to fix `file output will ack messages in pubsub before delivery`
- May involve complex behavior in interacting with beam API
- custom IO plugins would be competing with upstream implementation

**Comment by jklukas** [comment]
I would add to pros of Beam:

- great operational visibility through a UI that groups together logging, message throughput, metrics, and error rates

> bigquery streaming output does not preserve original message on exceptions

I'd call this is a limitation of BigQuery's `insertAll` API rather than Beam's API.

**Comment by relud** [comment]
> > bigquery streaming output does not preserve original message on exceptions
>
> I'd call this is a limitation of BigQuery's `insertAll` API rather than Beam's API.

If we wrote our own code to call `insertAll` then we could preserve a mapping between request row and original message. So it seems like a limit of `BigQueryIO.Write`, which I would count as Beam's API.

**Comment by relud** [comment]
Discussing this with @jklukas today resulted filing #380 and #381 as potential solutions for parts of `Known problems in beam`. I intend to work on each of these after load testing is complete, and expect them to take less than a week each to write and evaluate.

**Comment by relud** [comment]
i'm closing this as resolved. the sink is moving off of beam, and the decoder will continue to be on beam.
