### ISSUE TITLE
Metrics per doctype

### ISSUE THREAD

**Issue by jklukas** [mozilla/gcp-ingestion#379]
In the Decoder, emit metrics per doctype for incoming messages and error rates.

**Comment by trink** [comment]
I will provide a list of summary metrics we want to migrate and how they are partitioned.

**Comment by jklukas** [comment]
Translating this to Beam metrics that get to Stackdriver, we would likely simply maintain a map of `Counter`s keyed by `namespace, doctype, appname, appversion, channel, docVersion`. These counters are emitted to Stackdriver every 30 seconds.

So, there wouldn't be exactly the same concept of aggregation per minute. The counts would all increase monotonically with each sample, but we could derive rates and approximate per-minute aggregates from that data in Stackdriver.

**Comment by jklukas** [comment]
I'm deploying a first version of the decoder with these per-uri-group metrics and hitting a limit I was not aware of:

> Your Dataflow job already exceeds the maximum allowable number of custom metrics. Custom metrics exceeding the limit of 50000 are dropped by Dataflow.

We may need to aggregate on doctype alone.

**Comment by jklukas** [comment]
After limiting to only valid doctypes that we have a schema for, I was able to deploy a pipeline that emits metrics by the full coordinates `namespace, doctype, appname, appversion, channel, docVersion`. Empirically, there were ~2000 unique points. If we have ~10 metrics we want to track for each metric coordinate, that's ~10k separate metrics, getting to the same order as Dataflow's limit.

It also causes lag in the Dataflow UI and makes it difficult to find metrics of interest. I see two options here:

- cut scope and track metrics only per `namespace, doctype`, which brings the total number of metrics down by an order of magnitude
- track per-doctype metrics via explicit Stackdriver calls rather than using Beam's metrics interface

**Comment by trink** [comment]
At a minimum we need namespace, doctype, and doc version as that provides a direct mapping to our schema validation.   However, in this case I don't think stackdriver metrics are the best fit due to the high dimensionality and inability to handle the diagnostic information. A stackdriver log with a JSON payload (like above) feed into InfluxDB would probably be a better option for the numeric data, the diagnostic part may still be challenging but I believe we could manage everything with tags and the diagnostics would just be a different type of measurement.

**Comment by relud** [comment]
@jklukas another option is to output metrics to a pubsub topic, possibly aggregated by batch or something.

**Comment by jklukas** [comment]
For the time being, I'm going to move forward with a PR that adds Beam counters per `namespace, docType, version`. That keeps it to an operable number of metrics and will at least get us more familiarity with Stackdriver if it doesn't end up being useful long-term.

Feeding structured messages to InfluxDB can be a discussion and larger project to be prioritized separately. I'll create a new issue for that.
