### ISSUE TITLE
Need pub/sub topics with a random sample of data

### ISSUE THREAD

**Issue by trink** [mozilla/gcp-ingestion#396]
To reduce pub/sub costs the sample streams should be broken out into separate topics.  For anomaly detection we only require a partition on normalized channel and then use the following sample sizes for each:
1% of release
10% of beta
100% of nightly

**Comment by jklukas** [comment]
I assume this is talking about output from Decoder? Do we want to include all docTypes where `namespace=telemetry`?

**Comment by mreid-moz** [comment]
cc @acmiyaguchi as he's been working on sampled datasets in AWS land.

**Comment by jklukas** [comment]
@trink - This is being implemented in https://github.com/mozilla/gcp-ingestion/pull/517
