### ISSUE TITLE
Retain user agent string?

### ISSUE THREAD

**Issue by jklukas** [mozilla/gcp-ingestion#404]
In #359, we discussed retaining all attribute other than IP. I had forgotten that we also strip user_agent. It's my understanding that user_agent can have some privacy concerns, so we likely still don't want to ship it downstream for analysis, but it's unclear whether we should retain it for error output, etc.

Current behavior is that we strip user_agent. If we reprocess a message from error output, we simply skip the user agent parsing step. This may be the behavior we want.

The alternate would be to retain user_agent as an attribute, which would mean the user agent parsing code will run again when we reprocess a message.

cc @relud @whd

**Comment by whd** [comment]
I think we should treat UA the same as IP address, which sounds like the current behavior. In the AWS pipeline we only parse user agent for non-telemetry submissions, as the one case for which it's currently relevant in telemetry (whether we shipped the ping via pingsender or not) we have a specific header that we retain for that information. I believe we do keep the UA string in non-telemetry error messages, but we have never needed to reprocess for the UA and I don't think it's important to keep that functionality.

There are cases where our UA parsing code has needed to be updated (e.g. for fxa metrics and iOS UAs) but that was for logging data. In such events being able to reprocess with updated UA parsing from landfill should be sufficient (but let's hope this won't happen).

**Comment by jklukas** [comment]
Sounds good. Closing without changes.
