### ISSUE TITLE
Send aggregated metrics payloads to InfluxDB

### ISSUE THREAD

**Issue by jklukas** [mozilla/gcp-ingestion#410]
Breakout from #379. See https://github.com/mozilla/gcp-ingestion/issues/379#issuecomment-455680692 for a summary of what metrics were available in the AWS pipeline and the JSON format of payloads.

If metrics based on Beam counters sent to Stackdriver as proposed in #379 are not sufficient, we'll need to consider getting custom metrics payloads to InfluxDB, either via Stackdriver logging or a Pubsub topic.

**Comment by trink** [comment]
Direct insertion into InfluxDB is also an option https://docs.influxdata.com/influxdb/v1.7/tools/api_client_libraries/

**Comment by jklukas** [comment]
Closing this as #379 appears to be sufficient for our needs. We can reopen if that's not the case.
