### ISSUE TITLE
Implement namespace/docType aliases

### ISSUE THREAD

**Issue by fbertsch** [mozilla/gcp-ingestion#424]
For Glean, we have multiple namespaces that are all really using the same schema. We don't want to duplicate this (exponentially - every application, ping, and version!) in mozilla-pipeline-schemas. Instead we'd like to alias namespaces and docTypes.

This would work by keeping a file in GCS of aliases. For example, `org-mozilla-reference-browser/baseline` would be an alias for `glean/glean`. When doing schema validation, the JSON schema would be found using `glean/glean`. Otherwise, the pipeline would use the other namespace and docType for other transformations.

We could additionally consider adding the aliased namespace and docType as metadata to the ping.

**Comment by jklukas** [comment]
I assume we want to maintain different tables in BQ for each of these? It is only the schema validation step where we want to resolve the namespace/docType to a particular schema?

Let me push back a moment on this idea. Do we have a good sense of how many application/ping/version combinations will be introduced with Glean? Are we sure it warrants introducing a new concept (breaking the 1:1 mapping of namespace/docType to schema)?

With the existing structure of mozilla-pipeline-schemas, each of these namespace/docType/version combos need only be a trivial file with a reference to the `include` for the glean structure. It's straightforward to build a parser for that repository that has full knowledge of allowed docTypes and the associated schemas. I worry this would significantly complicate the ability for humans to comprehend and for computers to parse that repo.

**Comment by fbertsch** [comment]
Thanks for the feedback @jklukas! I'll answer inline.

> I assume we want to maintain different tables in BQ for each of these?
Right, definitely. This mapping is solely for validation.

> Do we have a good sense of how many application/ping/version combinations will be introduced with Glean? Are we sure it warrants introducing a new concept (breaking the 1:1 mapping of namespace/docType to schema)?
So far, we have 3 applications that implement glean, and it doesn't even have any data yet! Given the 4 additional mobile browsers, lockbox, and VR; we're looking at 10+ applications.

For pings, we have: baseline, metrics, events, crash, and activation. Additionally each application can send custom pings, so e.g. a sync ping. In total, >60 pings, each with the same schema.

> With the existing structure of mozilla-pipeline-schemas, each of these namespace/docType/version combos need only be a trivial file with a reference to the `include` for the glean structure

What we _really_ don't want is for anyone to have to do anything when adding a new glean ping except update their repository. For a new application, all we want is one change to the `repositories.yaml` file. From there we'd introduce schemas, tables, alerting, and dashboards for the application. We want this to be automated such that there's no delay.

**Comment by jklukas** [comment]
Thanks for getting me up to speed. Is it understood at this point what the file in GCS would look like, or is that TBD?

**Comment by fbertsch** [comment]
No plan, that is up to the implementer. As long as it can map any specific namespace/docType to another namespace/docType, that will suffice for our needs.

**Comment by jklukas** [comment]
> For a new application, all we want is one change to the `repositories.yaml` file. From there we'd introduce schemas, tables, alerting, and dashboards for the application. We want this to be automated such that there's no delay.

Is `repositories.yaml` a single file in some repository that points to the repositories using Glean? And then we'd need to have some process to scrape those repositories to generate the GCS file?

And are you intending for this issue to track the overall project of creating the machinery for generating the mapping file in GCS plus using that file in the Decoder job to follow the aliased schemas?

**Comment by fbertsch** [comment]
> Is `repositories.yaml` a single file in some repository that points to the repositories using Glean? And then we'd need to have some process to scrape those repositories to generate the GCS file?

Right - that lives in, and is deployed by, the probe-scraper.

This is not intended to track the entire pipeline, just the piece the "reading a alias mapping file, and using those aliases for schema validation".

**Comment by akkomar** [comment]
> For example, org-mozilla-reference-browser/baseline would be an alias for glean/glean. When doing schema validation, the JSON schema would be found using glean/glean

@fbertsch did you mean: `org-mozilla-reference-browser/baseline would be an alias for glean/baseline (...) JSON schema would be found using glean/baseline`?

**Comment by akkomar** [comment]
Resolved in #508 with more general solution to come.
