### ISSUE TITLE
Support numShards as a runtime parameter

### ISSUE THREAD

**Issue by jklukas** [mozilla/gcp-ingestion#435]
This would make @whd's life easier.

**Comment by jklukas** [comment]
FileIO allows passing `numShards` at runtime, but BigQueryIO does not; it's compile-time only. We could split out bq numShards to a separate parameter so that the file outputs can use a runtime numShards. Is that still helpful?

**Comment by whd** [comment]
I'm primarily concerned with FileIO being configurable to make reasonable batch sizes. Splitting the parameters seems like an OK way of supporting this, and hopefully `numShards` for bq doesn't need tuning.
