### ISSUE TITLE
Duplicates are dropped

### ISSUE THREAD

**Issue by whd** [mozilla/gcp-ingestion#446]
We should update the documentation if we're not going to stream all duplicates to the error stream: https://github.com/mozilla/gcp-ingestion/blob/master/docs/decoder.md#decoding-errors.

A separate discussion would be whether to in fact keep the duplicates as errors for downstream analysis. This would allow for more comprehensive parity monitoring. Deduping is interesting to me because the implementation is completely different on the different pipelines, but I don't feel strongly that we need to keep them. In the AWS pipeline, we generated metadata-only dedup messages for cost/efficiency purposes.

**Comment by jklukas** [comment]
> In the AWS pipeline, we generated metadata-only dedup messages for cost/efficiency purposes.

So, you expect we could get the same benefit in GCP by generating attribute-only dedup messages?

**Comment by whd** [comment]
I expect that we could more directly compare the deduplication systems via parity CEP monitoring if we generated attribute-only dedup messages to the error stream (in the AWS pipeline there's actually a telemetry.metadata topic for these messages, but they are all processed by the same system as errors).

I suspect in the long run we'll move toward monitoring based off of native metrics like the ones being currently generated, so I don't feel strongly that we should generate these messages in GCP, but in the near term, it would comparison easier (and the comparison is interesting).
