### ISSUE TITLE
Preserve non-schema'd telemetry as json

### ISSUE THREAD

**Issue by relud** [mozilla/gcp-ingestion#450]
option 1: whole body is an uncompressed json string in bigquery, table schema matches pubsub message
option 2: fields in body missing from schema are moved to an extras column with uncompressed json string, table schema matches existing schema plus extras column

**Comment by relud** [comment]
option 1 is the planned first-pass on this, because our first use-case is for telemetry doc types with no schema

**Comment by mreid-moz** [comment]
See also #270

**Comment by jklukas** [comment]
Capturing of non-schema'd json to an `additional_properties` field is included in this evolving PR: https://github.com/mozilla/gcp-ingestion/pull/536

**Comment by jklukas** [comment]
The above is merged.
