### ISSUE TITLE
Better handling of Redis connections

### ISSUE THREAD

**Issue by jklukas** [mozilla/gcp-ingestion#451]
Earlier this week, we saw the decoder get into a state where some messages were showing "Broken pipe" SocketExceptions and going to error output. @whd reported that Redis was healthy, but that a node had failed over the day previous. So the SocketException may be due to losing the connection and then not recovering with a new connection.

Some things we may want to do:

- Handle SocketException by attempting to instantiate a new Jedis instance
- Increase connection timeout (see https://github.com/xetorthio/jedis/issues/185 for discussion)
- Default to allowing messages to pass through if we are not able to get a response from Redis

cc @whd @relud - I believe we've had a conversation before about potentially defaulting to allowing messages through if Redis is unavailable. Does that sound like the right thing to do?

**Comment by whd** [comment]
> I believe we've had a conversation before about potentially defaulting to allowing messages through if Redis is unavailable. Does that sound like the right thing to do?

Yes.
