### ISSUE TITLE
All mobile pings are being marked as errors

### ISSUE THREAD

**Issue by jklukas** [mozilla/gcp-ingestion#455]
Reported by @trink

**Comment by trink** [comment]
i.e. Core ping, fennec release has 162757 errors and 310931 duplicates in the last hour (no valid submissions)

**Comment by fbertsch** [comment]
Is this happening on AWS, or just GCP?
Is this the schema that @jklukas put together, or the schema that Anthony was running? (Assuming it's the former).

**Comment by trink** [comment]
just GCP

**Comment by jklukas** [comment]
The GCP decoder is deduping based solely on document_id, but @trink indicates that the AWS pipeline keeps track of seen document_ids for each namespace/channel/version combo independently.

So, the current theory is that some mobile applications are reusing a single document_id for several different ping types.

**Comment by trink** [comment]
The conversion from GCP schema back to the current production schema was incomplete it was missing this special case: https://github.com/mozilla-services/lua_sandbox_extensions/blob/master/moz_telemetry/io_modules/decoders/moz_ingest/telemetry.lua#L254
