### ISSUE TITLE
Allow exception to bubble up if a configured resource doesn't exist

### ISSUE THREAD

**Issue by jklukas** [mozilla/gcp-ingestion#457]
We had a deploy of the structured ingestion decoder yesterday that happily ran with an invalid `--schemaLocation`. I believe that every record is trying to initialize the schema store and throwing an IOException.

For runtime configuration parameters, we should let an exception bubble up and stop execution if it's fairly obvious that the configured value is incorrect.

I'm thinking we define a new `ConfigurationException` for our project and make sure that our `MapElementsWithErrors` class does not send that particular exception to error output.

**Comment by jklukas** [comment]
cc @relud @whd

**Comment by relud** [comment]
that solution sounds good to me
