### ISSUE TITLE
Allow mirroring pings submitted with specific HTTP header to custom PubSub topic

### ISSUE THREAD

**Issue by akkomar** [mozilla/gcp-ingestion#458]
Glean clients will have an option to send "debug" pings tagged with specific HTTP header. We'd like to have these pings mirrored to separate PubSub topic (in parallel to the normal, decoded one) for easier consumption and processing.

Per discussion with @jklukas  this routing can be implemented in decoder. IIUC we'd need to allow configuring custom header->topic mapping there and mirror matching pings to separate topic.
This would involve reconfiguring edge server to attach debug header to messages, which can be achieved via `METADATA_HEADERS` configuration parameter.

Additionally:
* we need only validated pings to be published to custom topic
* @fbertsch mentioned that users also would very likely want to be able to query "debug" pings in common ping tables. I think we can allow this by attaching the header used for filtering in decoder to message metadata (I'm assuming metadata is stored in BigQuery - @jklukas could you confirm?)

**Comment by akkomar** [comment]
cc @relud

**Comment by jklukas** [comment]
> I'm assuming metadata is stored in BigQuery

Yes, BigQuery tables have a `metadata` struct for fields like this, but we need to provide the expected fields as part of BigQuery schema creation. So, we'd need to build logic into our jsonschema to BQ parser (cc @acmiyaguchi) to know that glean-based tables should have a `metadata.debug` field.

@akkomar - Do the "debug" pings have the same schema as others? The "debug" flag is just for making it easier to trace a debug flow? It sounds like we'd want to double-publish these payloads to the normal decoded topic and to the special glean debug topic.

**Comment by akkomar** [comment]
@jklukas:
> Do the "debug" pings have the same schema as others? The "debug" flag is just for making it easier to trace a debug flow?

Yes and yes. This is not intended for iterating on the schemas, but for validating in real-time that interactions on a device result in the correct data on our side.
One of the reasons for choosing request header for tagging was that it doesn't require any schema changes.

> It sounds like we'd want to double-publish these payloads to the normal decoded topic and to the special glean debug topic.

Yes, that's why I described this as "mirroring". I've edited issue description to make it clearer.

**Comment by jklukas** [comment]
Based on the needs documented here, I'm thinking the best architecture for handling this need would be an additional Dataflow job downstream of the decoder for structured ingestion. That would incur the expense of an additional subscriber to the `ingestion_decoded` topic, but would keep a better separation of concerns. We can look into melding this into the decoder in the future.

This need seems closely related to https://github.com/mozilla/gcp-ingestion/issues/396 which could be handled via a similar `Republisher` job on the `telemetry_decoded` topic.

**Comment by akkomar** [comment]
Sounds good. From engineering point of view I'm 100% for separate job.

I was under impression that cost of running multiple consumers on full decoded topic would be prohibitively high. Even if that's the case I think starting this way is not a bad idea.

**Comment by jklukas** [comment]
> I was under impression that cost of running multiple consumers on full decoded topic would be prohibitively high. Even if that's the case I think starting this way is not a bad idea.

Yes, we may need to revisit this decision in coming months.

**Comment by jklukas** [comment]
Had a discussion with @trink @whd and @mreid-moz today about this. @mreid-moz is going to schedule a follow-up meeting including @akkomar to get more context on use case.

The basic concern is about making sure any changes we make here meet the glean debug needs but do so in an extensible way such that this is not a special case that's difficult to maintain going forward as similar needs arise.

**Comment by akkomar** [comment]
This will be implemented in https://github.com/mozilla/gcp-ingestion/issues/479
