### ISSUE TITLE
Investigate deduplication scopes

### ISSUE THREAD

**Issue by jklukas** [mozilla/gcp-ingestion#460]
Per @trink, in the AWS pipeline, deduplication considers the entire URI. In the GCP pipeline, we are considering only the `document_id`. If an application used a single UUID to send multiple different ping types, we would be vulnerable to throwing out unique data in a way that was not possible in the AWS pipeline.

Storing the entire URI in Redis, however, would require ~100 bytes compared to the 2-byte UUID representation we're currently using.

**Comment by trink** [comment]
This was a discussion mreid, whd, and I had 4 years ago (but at that time the document id wasn't required to be a UUID it was just a string and we were worried about collisions (intentional or accidental) IIRC

**Comment by jklukas** [comment]
We effectively do this now, since we're relying on Dataflow-based deduplication on the `uri` attribute of messages.
