### ISSUE TITLE
Review docs in this repo, update to match current state

### ISSUE THREAD

**Issue by jklukas** [mozilla/gcp-ingestion#468]
Per request of @mreid-moz

**Comment by whd** [comment]
One specific instance, https://github.com/mozilla/gcp-ingestion/blob/master/docs/decoder.md#decoded-message-metadata-schema which I was going to point at in https://bugzilla.mozilla.org/show_bug.cgi?id=1553999 is probably missing some newer fields like `normalized_country_code`.
