### ISSUE TITLE
Topic and subscription naming conventions

### ISSUE THREAD

**Issue by whd** [mozilla/gcp-ingestion#476]
Stage is currently structured like so. For each top-level `TOPIC` (ingestion, telemetry, tls_error_reports, stub_installer), we have the following pubsub topics:

    $TOPIC (raw data)
    $TOPIC-decoded
    $TOPIC-errors
    $TOPIC-{NEXT_COOL_DERIVED_THING}

The corresponding subscriptions for each `JOB_TYPE` (decoder, landfill, sink, sink-error) look like:

    $JOB_TYPE-subscription-$TOPIC (the top-level topic)

There's also a special case `decoder-dedup-subscription-$TOPIC (the top-level topic)` used by the decoder.

The `TEMPLATE_JOB_TYPE`s (sink, bqsink, decoder) and their mapping to current job types are presently:

    sink -> landfill, sink-error
    bqsink -> sink
    decoder -> decoder

There are plans to add a decoded GCS sink (this was always documented but I hadn't set it up in stage) and the new Republisher `JOB_TYPE`. The GCS sink would use the existing sink `TEMPLATE_JOB_TYPE`, while Republisher will also be a new `TEMPLATE_JOB_TYPE`.

This has gotten a bit messy, and I want to formalize naming conventions and eventually document it.

My proposed formalization is as follows:

Topics:

    $TOPIC-raw
    $TOPIC-decoded
    $TOPIC-errors
    $TOPIC-${NEXT_COOL_DERIVED_THING}

Subscriptions:

    $TEMPLATE_JOB_TYPE-subscription-$TOPIC (the actual topic being consumed)

`$TEMPLATE_JOB_TYPE` can be generalized as the "primary application identifier" for non-Dataflow jobs, but we don't have any at present. No special case will be required for the dedup subscription since it will now be the Republisher subscription. The main change here is that `JOB_TYPE` e.g. `landfill` is no longer necessary, since subscriptions map into Dataflow jobs without them.

Any feedback on the above structure is welcome. Some particular considerations I would like input on:

* Whether to prefix or suffix with `$TOPIC` for subscriptions.
* Whether to rename the `TEMPLATE_JOB_TYPE` "sink" to "gcssink" or similar.
* Whether to include `-subscription-` in the subscription name, since it is redundant.
* Whether to suffix the raw topic with `-raw` and/or drop the `-decoded` suffix on the decoded topic.
* What the top-level topic names should be. Minimally we're planning on changing "ingestion" to "structured" as short for "structured ingestion" since "ingestion" is awfully vague.
* `-` or `_` for delimiters

**Comment by jklukas** [comment]
>     * Whether to rename the `TEMPLATE_JOB_TYPE` "sink" to "gcssink" or similar.

Yes, I would like a more parallel name between the bq and gcs sinks. Let me propose the following concrete example of a subscription name:

    telemetry-decoded.gcs-sink

So topic names and job names would each be built with hyphens and then we use `.` as a separator between them for subscription names.

>     * Whether to include `-subscription-` in the subscription name, since it is redundant.

I'd prefer to remove it.

>     * Whether to suffix the raw topic with `-raw` and/or drop the `-decoded` suffix on the decoded topic.

I like having the `-raw` and `-decoded` suffixes.

>     * What the top-level topic names should be. Minimally we're planning on changing "ingestion" to "structured" as short for "structured ingestion" since "ingestion" is awfully vague.

My vote is for `telemetry-raw` and `structured-raw`

>     * `-` or `_` for delimiters

I prefer dashes, and think we might want to use periods as well as discussed in the example above.

**Comment by whd** [comment]
As to https://github.com/mozilla/gcp-ingestion/pull/517#discussion_r272615136, I'll respond with my thoughts on the next round of derived pubsub topic names here.

Semantically I think we want to establish the following naming convention for derived topics.

    INPUT_TOPIC[-TRANSFORM...]

where `-TRANSFORM` is the transform being applied. `TRANSFORM`s can be chained, so
we might conceivably end up with a topic like:

    telemetry-decoded-doctype_event-sampled-debug

by running Decoder -> Republisher(split out event) -> Republisher(1% sample)-> Republisher(debug).

The only special case is that the Decoder transform, which can only
apply to "-raw" streams, replaces the "-raw" suffix
with "-decoded".

Semantically, I've been differentiating `-` and `_`, where `-` splits primary
identifiers/transforms and `_` splits within a primary identifier. This has
hitherto only been used for the top level names e.g. `stub_installer-decoded`,
`tls_error_reports-raw` but has some considerations as we add these new derived
topics. It would mean, if we decide each dataflow job maps to one level of
`TRANSFORM`, that we would want `TRANSFORM` for Republisher to map to topics
like:

    projects/moz-fx-data-shar-nonprod-efed/topics/telemetry-decoded-doctype_event
    projects/moz-fx-data-shar-nonprod-efed/topics/telemetry-decoded-sampled_nightly
    projects/moz-fx-data-shar-nonprod-efed/topics/telemetry-decoded-sampled_beta
    projects/moz-fx-data-shar-nonprod-efed/topics/telemetry-decoded-sampled_release
    projects/moz-fx-data-shar-nonprod-efed/topics/structured-decoded-debug

but it probably makes equal sense to consider "doctype" and "sampled" as
`TRANSFORM`s themselves, as originally proposed:

    projects/moz-fx-data-shar-nonprod-efed/topics/telemetry-decoded-doctype-event
    projects/moz-fx-data-shar-nonprod-efed/topics/telemetry-decoded-sampled-nightly
    projects/moz-fx-data-shar-nonprod-efed/topics/telemetry-decoded-sampled-beta
    projects/moz-fx-data-shar-nonprod-efed/topics/telemetry-decoded-sampled-release
    projects/moz-fx-data-shar-nonprod-efed/topics/structured-decoded-debug

Overall I'm undecided. In this second form, splitting on "-", we wouldn't be able to tell that both "doctype" and "event" were the result of a single dataflow job. But we potentially don't care.

The particular consideration from an application perspective with respect to the `-` splits naming convention is that doctypes would need to be normalized to underscores in topic names e.g. "new-profile" would need to map to "new_profile". Mapping to similar conventions as the bigquery table layout is a secondary consideration.

Ultimately, if we don't care about `-` being able to split the topic in a meaningful way (e.g. to identify its lineage) this convention is largely unnecessary. I suspect our topology and job complexity will not grow to the point where this will end up mattering too much, but I felt it worthy of at least writing down and discussing.

/CC @jklukas for thoughts.

**Comment by jklukas** [comment]
+1 to your proposed convention of using underscores within the identifier for a logical transform. It keeps with the dataflow job naming scheme. Mixing underscores and dashes isn't aesthetically pleasing, but I do find the meaning of `telemetry-decoded-doctype_event` more clear at a glance compared to `telemetry-decoded-doctype-event`.

> doctypes would need to be normalized to underscores in topic names e.g. "new-profile" would need to map to "new_profile". Mapping to similar conventions as the bigquery table layout is a secondary consideration.

I think it absolutely makes sense to normalize docTypes for use in topic names, and the fact that this matches naming of tables in BQ is a good thing. If we end up splitting out per-docType topics from structured ingestion, this will get uglier since namespace will also need to be in the topic name (so we'd have `activity-stream/impression-stats` map to `structured-decoded-doctype_activity_stream_impression_stats`) but the name still ends up being pretty easily parsable by both humans and machines.
