### ISSUE TITLE
Add metadata fields for core pings

### ISSUE THREAD

**Issue by mreid-moz** [mozilla/gcp-ingestion#477]
There is a lengthy set of metadata fields in the AWS pipeline [here](https://docs.telemetry.mozilla.org/datasets/pings.html#ping-metadata), and an automated list of observed fields [as described here](https://bugzilla.mozilla.org/show_bug.cgi?id=1448343#c2). It appears that the `telemetry_dev.core_v10` table currently only contains `document_id`, `geo_country`, and `geo_city`.

I propose that we add the following:
- Any headers we're currently paying attention to, including `Date`, `DNT`, and `X-PingSender-Version`
- geoSubdivision1
- geoSubdivision2
- sampleId -> crc32(clientId) % 100

And consider also adding normalized fields:
- normalizedChannel
- normalizedOSVersion
- normalizedOs
- normalizedAppName

**Comment by jklukas** [comment]
We don't do any field normalization currently in the GCP pipeline, so we should likely break that out to a separate issue. If you can point me to the code for creating those normalized fields in the AWS pipeline, that would be helpful.

We also probably want to include all the URI component attributes:

- app_name
- app_version
- app_update_channel
- app_build_id

Note that these are all lower_snake_case in the GCP pipeline and those names will appear in the `metadata` struct. You'll have to fight me if you want to use camelCase to stay consistent with the old tables. Not really, but let me know if it's something we need to discuss.

**Comment by jklukas** [comment]
I went ahead and added the geo subdivision fields and those are getting populated now in core_v10 and core_v9.

**Comment by mreid-moz** [comment]
> We also probably want to include all the URI component attributes:
>     * app_name
>     * app_version
>     * app_update_channel
>     * app_build_id

These are all available [inside the `telemetry` payloads](https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/telemetry/data/common-ping.html) too, so I am not sure we need to add them - it has been a source of confusion in the past that these pieces of data exist in multiple places after they're stored, and whether it's possible for them to differ, and if so which we should prefer. 

> Note that these are all lower_snake_case in the GCP pipeline and those names will appear in the `metadata` struct. You'll have to fight me if you want to use camelCase to stay consistent with the old tables. Not really, but let me know if it's something we need to discuss.

+1 for `lower_snake_case` and consistency within the GCP pipeline.

Shall we also split out the handling of HTTP headers as a separate issue?

**Comment by jklukas** [comment]
Note that the `telemetry-core-parquet` dataset is partitioned by submission_date_s3, app_name, and os.

We aren't using clustered tables yet in BigQuery, but we may adopt that in the future. We already are promoting `submission_date` from metadata to a top-level field in the GCS pipeline before writing to BigQuery so that we can use it as the table's partitioning field. We may want to do similar for `app_name` and `os` so they can be used as clustering fields in the future. But we don't want this decision to be table-specific, so maybe we want to move more of these fields to top level. Perhaps that needs a breakout issue too for discussion.

**Comment by mreid-moz** [comment]
There are definitely several things in play here:
- which available fields we capture in the `metadata` struct
- where those `metadata` fields should live (inside that struct or at the top-level)
- handling computed fields (which may or may not be part of `metadata`), such as [`sample_id`](#482) and [normalized fields](#478)
- [headers](#481) as a potentially-special case
- partitioning and clustering of tables

We can address some of them individually, but it may be a good idea to sketch out a high-level plan to help keep the overall approach clear.

**Comment by mreid-moz** [comment]
Oh, and we should also consider developing a JSONSchema for the metadata added by the pipeline, which we could version based on the ingestion code and incorporate into the schema transpiler.

**Comment by jklukas** [comment]
> We can address some of them individually, but it may be a good idea to sketch out a high-level plan to help keep the overall approach clear.

> Oh, and we should also consider developing a JSONSchema for the metadata added by the pipeline, which we could version based on the ingestion code and incorporate into the schema transpiler.

Good ideas. I will think about this and see if I can put together a proposal.

**Comment by jklukas** [comment]
> These are all available [inside the `telemetry` payloads](https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/telemetry/data/common-ping.html) too, so I am not sure we need to add them - it has been a source of confusion in the past that these pieces of data exist in multiple places after they're stored, and whether it's possible for them to differ, and if so which we should prefer.

This pertains to main pings and event pings, but `core` pings in particular don't follow the common ping format, so we'd only have this data available if we added from the parsed URI elements.

Is there any resolution as to whether we should prefer values put in the URI or values in the payload for those pings that have both available?

**Comment by jklukas** [comment]
This is happening as of https://github.com/mozilla/gcp-ingestion/pull/542
