### ISSUE TITLE
Add "normalized" attributes (normalizedChannel, etc.)

### ISSUE THREAD

**Issue by jklukas** [mozilla/gcp-ingestion#478]
@mreid requested that we get the following fields into BQ in https://github.com/mozilla/gcp-ingestion/issues/477:

- normalizedChannel
- normalizedOSVersion
- normalizedOs
- normalizedAppName

We don't currently produce those. I'll need to know where to look to find the old pipeline's logic for these.

**Comment by whd** [comment]
Most likely https://github.com/mozilla-services/lua_sandbox_extensions/blob/master/moz_telemetry/modules/moz_telemetry/normalize.lua
