### ISSUE TITLE
Add sample_id to BigQuery tables

### ISSUE THREAD

**Issue by jklukas** [mozilla/gcp-ingestion#482]
Breakout from #477 

We will want to have `sample_id` available (`crc32(clientId) % 100`). BQ does not have a crc32 function, so we will need to populate that as part of the pipeline. Further, we may want this to be a top-level field so it can be used for clustering.

We will likely want to make this an `int` rather than `string` as it is in the parquet datasets.

**Comment by jklukas** [comment]
Once this is in place, we can update the Republisher to produce monitoring topics based on sample_id rather than random numbers.

And per @whd:

> This sample id (and whether it matches the AWS pipeline's) is another easy comparison point across pipelines for validation.

**Comment by relud** [comment]
thought: we could make this `crc32(clientId)`, and handle `% 100` downstream so that we can select even smaller datasets. This would be especially useful for using clustering in BigQuery to get very small samples.

**Comment by jklukas** [comment]
> This would be especially useful for using clustering in BigQuery to get very small samples.

Tell me more. Would we cluster on the crc32 value directly?

**Comment by relud** [comment]
yeah, and then we would do something like `SELECT ... WHERE crc32 < MAX_CRC32/100`

**Comment by relud** [comment]
Now that I think about it, doing `SELECT ... WHERE MOD(crc32, 100) = 42` probably wouldn't actually reduce cost, and that's v different from the sample `crc32 < MAX_CRC32/100`, so IDK if this will actually be useful.

**Comment by jklukas** [comment]
I think I'm inclined to target just the existing `sample_id` for simplicity. But allowing smaller samples would be a good thing to keep in mind for a `sample_id_v2` that uses a different hashing algorithm like MD5 with better avalanche behavior.

**Comment by relud** [comment]
that sounds great

**Comment by jklukas** [comment]
See https://github.com/mozilla/gcp-ingestion/pull/526

**Comment by jklukas** [comment]
sample_id is now being produced in the Decoder and I've added a corresponding field to the core_v9 and core_v10 tables. Watching to see new data flow in.

**Comment by jklukas** [comment]
sample_id is being populate in core tables. Closing.
