### ISSUE TITLE
Preserve edge timestamp across the tee

### ISSUE THREAD

**Issue by relud** [mozilla/gcp-ingestion#496]
If I understand correctly we aren't using the value of `X-Pipeline-Proxy` for anything, so in the tee we could set the value of that header to the `submission_timestamp` from the AWS edge (or maybe something equivalent) and in the decoder we could use that value to in place of the `submission_timestamp` set by ingestion-edge. Maybe the decoder would also monitor the lag between the two.

This should allow us to eliminate timestamp lag, which should make it easier to assess the gcp-ingestion pipeline and make a production data source.

cc @whd @jklukas

**Comment by whd** [comment]
This is another candidate for #468 since we don't explicitly document this behavior anywhere.
