### ISSUE TITLE
Unexpected ping increases in activity_stream.impression_stats

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/gcp-ingestion#498]
Came across this during the data validation for Activity Stream,

* Monday, 11th March
RS (Redshift): DAU (7,080), impressions (212,500), clicks (1,489)
BQ (BigQuery): DAU (6,142), impressions (179,758), clicks (1,238)

* Tuesday, 12th March
RS: DAU (7,033), impressions (212,059), clicks (1,400)
BQ: DAU (7,591), impressions (204,856), clicks (1,385)

* Since 13th March, DAU, total # of impressions and clicks in BQ were about 2-3x more than RS. E.g. DAU (14,588), impressions (510,000) on 13th March

BQ query for Impressions/Clicks: https://sql.telemetry.mozilla.org/queries/61901/source
BQ query for DAU: https://sql.telemetry.mozilla.org/queries/61918/source
RS queries: https://sql.telemetry.mozilla.org/queries/61919/source

**Comment by jklukas** [comment]
I took a look at `document_id`s and the duplicate rate is well under 1%, so that doesn't appear to be a factor in overcounting.

**Comment by jklukas** [comment]
I do see `impression_id` being duplicated hundreds or thousands of times, though this may be expected. I can't recall the semantic significance of `impression_id`.

**Comment by ncloudioj** [comment]
> I do see impression_id being duplicated hundreds or thousands of times, though this may be expected. I can't recall the semantic significance of impression_id.

Yes, you can treat `impression_id` as the UUID for each user here, so it's expected to see duplicates as every single ping, sent from the same user, would have the same `impression_id`.

**Comment by jklukas** [comment]
I'm seeing about as many pings with release_channel = "aurora" as I do "nightly", so it looks like we're getting data from Developer Edition flowing through the BQ pipeline.

If I filter to `release_channel IN ('nightly', 'aurora')`, I see DAU that's consistently a bit higher in RS vs. BQ over the past week. I think this may explain the discrepancy.

**Comment by ncloudioj** [comment]
Nice catch, perhaps the DE already switched to 67 on 13th March.

Let me add one more filter for `release_channel` in my BQ queries so we can focus on Nightly first. Let's see how it goes.

**Comment by ncloudioj** [comment]
Yep, with `GROUP BY release_channel`, those queries yield consistent DAU, impressions, and clicks with those on 11th and 12th March.

So this was caused by the DE channel switch, closing this issue now.

Thanks for the investigation! @jklukas
