### ISSUE TITLE
Consider developing a schema for the metadata added by the decoder.

### ISSUE THREAD

**Issue by mreid-moz** [mozilla/gcp-ingestion#499]
Breaking out part of the discussion in #477:
> Consider developing a JSONSchema for the metadata added by the pipeline, 
> which we could version based on the ingestion code and incorporate into the 
> schema transpiler.

**Comment by acmiyaguchi** [comment]
One idea to start is to programmatically insert the metadata section into the avro schema as a `Map<String, String>` here:

https://github.com/mozilla/gcp-ingestion/blob/dc7429954b8f2bd5d0a87b2867105b0e2c2001a6/ingestion-beam/src/main/java/com/mozilla/telemetry/avro/PubsubMessageRecordFormatter.java#L27-L32

A downside of this approach is the generated BigQuery schema in mps will be different by this new section. Additionally, once the map is converted into a repeated key-value struct in BigQuery, it'll likely be tricky to convert into a struct in the case of a table migration without a UDF.

**Comment by jklukas** [comment]
> One idea to start is to programmatically insert the metadata section into the avro schema as a Map<String, String>

Given the evolving conversation in the past few days, I'm feeling pretty confident that we have a way forward for defining the nested metadata structure in a JSON schema, and merging that in as part of generation of avro and bq schemas. So I think we can safely avoid taking the intermediate step of adding a metadata map to the avro schema.

**Comment by jklukas** [comment]
Added in https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/312
