### ISSUE TITLE
Investigate clustered tables

### ISSUE THREAD

**Issue by jklukas** [mozilla/gcp-ingestion#525]
[Table clustering](https://cloud.google.com/bigquery/docs/clustered-tables) is a beta BigQuery feature that would allow us to achieve some of the same benefits we get from partitioning Parquet data on multiple dimensions.

For our use, I'm imagining the following clustering scheme for derived tables (updated one per day):

- submission_date (partitioning field)
- sample_id
- additional columns per table?

For "base" tables that our Beam jobs are loading data into throughout the day, we'd have the following clustering scheme:

- submission_timestamp (partitioning field)
- sample_id
- additional columns per table?

For base tables, we may find that we get no immediate benefit from clustering because data is being loaded throughout the day and landing in the table in unsorted order. In order to get benefits of clustering, we may need to have Airflow do a nightly query on each base table to "close" the previous day's data. This is based on the following in the docs:

> Over time, as more and more operations modify a table, the degree to which the data is sorted begins to weaken, and the table becomes partially sorted. In a partially sorted table, queries that use the clustering columns may need to scan more blocks compared to a table that is fully sorted. You can re-cluster the data in the entire table by running a SELECT * query that selects from and overwrites the table (or any specific partition in it). In addition, any arbitrary portion of the table can be re-clustered using a DML MERGE statement

Current examples of partitioning in the AWS Parquet world are `telemetry-core-parquet` which partitions on app_name and os in addition to submission_date.

Note that, like with partitioning, nested fields may not participate in clustering, so we'll need to make sure that any fields we want to use for clustering appear at the top level.

**Comment by jklukas** [comment]
I created a clustered table via:

```
CREATE TABLE
  tmp.klukas_core_clustered
partition by submission_date_s3
cluster by sample_id, client_id, os, country
AS
SELECT 
  *,
  metadata.geo_country AS country,
  ABS(MOD(FARM_FINGERPRINT(client_id), 100)) AS sample_id
FROM `moz-fx-data-derived-datasets.telemetry.telemetry_core_parquet_v3` 
WHERE submission_date_s3 BETWEEN "2019-04-01" AND "2019-04-28"
```

## Filtering by sample_id

The following query filters to a single sample_id:

```
SELECT client_id
FROM `moz-fx-data-derived-datasets.tmp.klukas_core_clustered` 
WHERE sample_id = 0
```

Logically, it should only need to scan 1% of the data. BQ's preview reports that it will process 102.8 GB, but the executed query indicates bytes processed as 1.56 GB, so 1.5% of the predicted data.

BigQuery lives up to its promise on this one.

## LIMIT on a clustered table

Here's an interesting (as far as I can tell undocumented) bonus of clustered tables. It appears that LIMIT is able to return without scanning the whole shebang.

This query on `telemetry_core_parquet` is predicted to scan 3.7 GB and indeed scans that much:

```
SELECT client_id
FROM `moz-fx-data-derived-datasets.telemetry.telemetry_core_parquet_v3` 
WHERE submission_date_s3 = "2019-04-01" 
LIMIT 1000
```

The equivalent query on the clustered table is predicted to scan the same 3.7 GB, but only scans 38 MB:

```
SELECT client_id
FROM `moz-fx-data-derived-datasets.tmp.klukas_core_clustered` 
WHERE submission_date_s3 = "2019-04-01" 
LIMIT 1000
```

**Comment by jklukas** [comment]
## Filtering with compound clustering keys

Consider a new clustered table:

```
CREATE TABLE
  tmp.klukas_core_clustered_v2
PARTITION BY
  submission_date_s3
CLUSTER BY
  sample_id,
  country,
  os AS
SELECT
  *,
  metadata.geo_country AS country,
  ABS(MOD(FARM_FINGERPRINT(client_id), 100)) AS sample_id
FROM
  `moz-fx-data-derived-datasets.telemetry.telemetry_core_parquet_v3`
WHERE
  submission_date_s3 BETWEEN "2019-04-01"
  AND "2019-04-28"
```

Now, let's make a query that filters only on the second of the three clustering keys (country):

```
SELECT client_id, os
FROM `moz-fx-data-derived-datasets.tmp.klukas_core_clustered` 
WHERE country = 'FI'
```

The preview predicts scanning 112 GB and it indeed scans the full 112 GB.

The BQ docs do indicate:

> the order of columns you specify is important

It looks like the sorting here is likely absolute rather than interleaved, so there's no way for the query engine to avoid scanning blocks unless the filter/grouping follows the clustering keys exactly.

**Comment by jklukas** [comment]
See https://github.com/mozilla/gcp-ingestion/issues/610

**Comment by jklukas** [comment]
Conclusion from #610 is that we can't currently support loading data directly into clustered tables, so we can only consider clustering for derived datasets at the moment.

**Comment by jklukas** [comment]
## Sample_id is a good first clustering key

For the case of `core` pings, we can argue that `app_name` is a more important filter than `sample_id`, so we may want to put that first. It turns out, though, that `sample_id` is a particularly good first clustering key because it's so uniform. For a sufficiently large table, each `sample_id` is likely to span many blocks, meaning that the secondary clustering key is also likely to be across many blocks.

If we cluster by `app_name, sample_id`, however, many app name are relatively small, so won't span many blocks and each block will contain a wide range of sample_ids. That means that filtering on sample_id isn't very efficient.

To demonstrate, we created two tables that cover a month of `core` pings, clustered the two different ways:

```
CREATE TABLE
  `moz-fx-data-derived-datasets.telemetry.klukas_tcp_sample_id`
PARTITION BY
  submission_date_s3
CLUSTER BY
  sample_id,
  app_name AS
SELECT
  ABS(MOD(farm_fingerprint(client_id), 100)) AS sample_id,
  *
FROM
  `moz-fx-data-derived-datasets.telemetry.telemetry_core_parquet_v3`
WHERE
  submission_date_s3 BETWEEN "2019-05-01"
  AND "2019-05-30"

CREATE TABLE
  `moz-fx-data-derived-datasets.telemetry.klukas_tcp_sample_id`
PARTITION BY
  submission_date_s3
CLUSTER BY
  sample_id,
  app_name AS
SELECT
  ABS(MOD(farm_fingerprint(client_id), 100)) AS sample_id,
  *
FROM
  `moz-fx-data-derived-datasets.telemetry.telemetry_core_parquet_v3`
WHERE
  submission_date_s3 BETWEEN "2019-05-01"
  AND "2019-05-30"
```

Then we run a counting query `SELECT count(sample_id), count(app_name)`. Without a filter, the query scans 41.4 GB.

If we filter for `sample_id = 0`, we get the following effective scan sizes:

- Clustered by sample_id first: 0.5 G
- Clustered by app_name first: 2.7 GB

If we filter for `app_name = 'Focus'`, we get the following effective scan sizes:

- Clustered by sample_id first: 39.4 G
- Clustered by app_name first: 2.3 GB

So, clustering by sample_id first gives us a 5x boost in the case where we're filtering by sample_id and it's only ~15% worse when filtering by app_name. Conversely, the table clustered first by app_name ends up scanning almost the entire table for the case where we want to filter only on sample_id.

**Comment by jklukas** [comment]
## Sample_id may be a good secondary clustering key

`app_name` is heavily skewed in the `core` tables. About 75% of the table has `app_name = Fennec` whereas `app_name = Zerda` is about 1% of the table.

If we cluster by `app_name, sample_id`, Fennec rows are going to be split across many blocks, so each block is going to contain only a single sample_id or a small subset of sample_ids. Thus, if we're filtering by sample_id, we can still get an efficiency boost by skipping blocks that definitely don't contain the desired sample_id. Smaller apps may be contained in only a few blocks, so sample_id won't be distinct and we won't get the boost there.

If we cluster by `sample_id, app_name`, it appears that we get almost no benefit when filtering on app_name. I believe this means that each sample_id is only getting split across a few blocks, so blocks are relatively heterogeneous in app_name.

This effect may depend a lot on data size. I am going to perform an experiment where we put much more core data in a single partition to see if we get better efficiency from the clustering.

**Comment by jklukas** [comment]
## Clustering becomes more efficient with larger partitions

To continue with the investigation of `core` pings but see the effect of larger data, I created another variant of the table that is "partitioned" on a static field so that all data goes to a single partition (clustering requires that we're using a partitioned table):

```
CREATE TABLE
  `moz-fx-data-derived-datasets.telemetry.klukas_tcp_unpartitioned`
PARTITION BY
  static_date
CLUSTER BY
  sample_id,
  app_name AS
SELECT
  ABS(MOD(farm_fingerprint(client_id), 100)) AS sample_id,
  current_date() as static_date,
  *
FROM
  `moz-fx-data-derived-datasets.telemetry.telemetry_core_parquet_v3`
WHERE
  submission_date_s3 BETWEEN "2019-01-01"
  AND "2019-05-30"
```

So, `app_name` is the secondary clustering key, but we get much more efficient filtering on app_name than we did with smaller partitions:

```
SELECT
  count(sample_id), count(app_name)
FROM
  `moz-fx-data-derived-datasets.telemetry.klukas_tcp_unpartitioned`
  where app_name = 'Zerda'
```

That query should nominally scan 200 GB, but scans only 1.7 GB.

So at this scale, the order in which we define our clustering keys becomes less important because the data spans enough blocks that each block is likely to contain only a single value of the primary key and only a single value or small range of the second key.

**Comment by relud** [comment]
clustering is now GA and enabled on all ping tables, with the default clustering being `normalized_channel` then `sample_id`.
