### ISSUE TITLE
Make decoder errors available in BigQuery

### ISSUE THREAD

**Issue by akkomar** [mozilla/gcp-ingestion#529]
For analyzing and fixing issues with client-side telemetry libraries, it would be useful to have decoder errors available in BigQuery. This does not need to be a long term storage, last {7-30} days would probably be enough. Schema of the tables does not need to be strict - it should be fine to store json error messages in a string column with additional columns for message attributes.

Possible implementations include:
* periodic loads of error messages from GCS
* setting up a BQ sink from `*_error` topics

cc @relud

**Comment by relud** [comment]
setting up on-demand loads from GCS using the bigquery transfer service seems like the easiest option. we just need to define the table has having a sufficiently filled out attributes schema, and then it's no change at all.

**Comment by jklukas** [comment]
We could also consider dropping the payload and streaming attribute-only messages to a table in BQ, which would make this path usable as a near-real-time debugging tool.

**Comment by relud** [comment]
I'm betting that payload is actually *really* relevant to debugging decoder errors

**Comment by relud** [comment]
also, we could store messages as avro in gcs and make this an external table

**Comment by jklukas** [comment]
This is complete. We now populate tables in the `payload_bytes_error` dataset in BQ.
