### ISSUE TITLE
Make Avro an option of outputFileFormat instead of outputType

### ISSUE THREAD

**Issue by whd** [mozilla/gcp-ingestion#538]
As currently implemented, the avro sink requires a new dataflow template, since `outputType` is a compile-time parameter. We have `outputFileFormat`, a runtime parameter, which we should use instead, if possible. That way we can reuse the existing gcs sink template. Semantically I think this makes sense as avro is a file format analogous to json text etc.

If configuring avro exclusively with runtime parameters on top of the existing gcs sink template isn't possible, updating the README to this effect and with examples would be useful.

Perhaps unrelated, I'm seeing both `--schemasLocation` and `--schemaLocation` options in IRC conversations and the code; that should probably be cleaned up.

/CC @acmiyaguchi

**Comment by jklukas** [comment]
Indeed, we have a duplicated option. Will fix. 

Otherwise, avro needs to be a separate outputType since it's a substantially different code path than the file-based ones. We can revisit in the future as we further consider how avro fits in.
