### ISSUE TITLE
Configure Decoder with initial schema aliasing configuration for developer builds

### ISSUE THREAD

**Issue by akkomar** [mozilla/gcp-ingestion#540]
It would be useful for mobile developers to have support for `.debug` flavors of apps in Glean Debug View.

Currently pings from these apps won't pass validation. In order to make this possible, we'd need to use schema aliasing mechanism introduced in #508. Despite that we don't have the configuration generation process ready yet, we can deploy minimal aliasing spec file to a chosen GCS location and make Decoder use it.

Later, when the config generator is ready it would overwrite this manually-generated file.

For now we'd need following configuration to be deployed:
```json
{
  "aliases": [
    {
      "alias": "org-mozilla-samples-glean-debug/baseline",
      "base": "glean/baseline"
    },
    {
      "alias": "org-mozilla-samples-glean-debug/metrics",
      "base": "glean/metrics"
    },
    {
      "alias": "org-mozilla-samples-glean-debug/events",
      "base": "glean/events"
    },
    {
      "alias": "org-mozilla-fenix-debug/baseline",
      "base": "glean/baseline"
    },
    {
      "alias": "org-mozilla-fenix-debug/metrics",
      "base": "glean/metrics"
    },
    {
      "alias": "org-mozilla-fenix-debug/events",
      "base": "glean/events"
    }
  ]
}
```

**Comment by akkomar** [comment]
@fbertsch does this sound good considering your plans around Probe Scraper and Glean config generation?

**Comment by akkomar** [comment]
I've put the initial config on GCS: `gs://spark-bigquery-dev/schema_aliases/201904291600_schema_aliases.json`.

@whd can we move this to the proper configuration bucket and deploy the Decoder with `--schemaAliasesLocation` option pointing to this file? Also let me know if I can do anything else to help.

**Comment by whd** [comment]
I've [deployed this](https://github.com/mozilla-services/cloudops-infra/commit/8018313ab41745f4434c923d704ca54a41d3daa4).
