### ISSUE TITLE
Discuss: What reprocessing pathways do we need to support?

### ISSUE THREAD

**Issue by jklukas** [mozilla/gcp-ingestion#560]
In https://github.com/mozilla/gcp-ingestion/issues/359, we discussed a need to maintain all the original attributes we receive from the edge (except for IP, which is too sensitive) when writing error output, such that error output can be run directly back through the Decoder with updated logic.

Near the end of the Decoder logic, we previously wrote all attributes into the payload in the `ParsePayload` transform. As of #542, we are saving only a specified subset of attributes into a nested metadata structure.

Two questions have come up:

1. Should we include the raw uri as a metadata field in the payload?
2. Do we need to support reprocessing of error output from the BQ streaming sink (where BQ passes us back the failed payload, but not the attributes)? See #216.

Raw URI is currently necessary to send a payload back through the Decoder, but I think all of our use cases for sending data back through the Decoder would include saved attributes. So, I believe we can rely on the `uri` attribute and don't strictly need to save uri in the payload to support any of our use cases. The question on uri then becomes whether there's a data risk to saving the uri since clients could potentially put sensitive information in those fields. That said, we don't do any validation on the fields we parse out of the uri, so we are still vulnerable to getting an SSN or other sensitive info into `app_build_id`, for example, which we _do_ save in the payload and expose as a field in BQ.

I can't think of a reason BQ streaming errors would need to be put back through the decoder; we'd only need to send them back through the BQ sink job. As long as we have doctype, namespace, and version saved in the payload, we should have all the necessary info to route the message to the correct table.

**Comment by jklukas** [comment]
cc @whd @relud

**Comment by mreid-moz** [comment]
For consideration: should we support reprocessing of documents we discard due to missing `docVersion` per #629 ?

**Comment by mreid-moz** [comment]
we should support reprocessing of documents for which we later add a schema per #630

**Comment by relud** [comment]
I believe this is resolved. At this point we support decoder reprocessing from raw and decoded payload bytes tables, and we can do in-place modifications of stable and live tables as-needed.
