### ISSUE TITLE
Recreate core_v10 as clustered on submission_timestamp

### ISSUE THREAD

**Issue by jklukas** [mozilla/gcp-ingestion#610]
I'm working on a proposal for transitioning to clustered tables, and I suspect we'll get value out of using submission_timestamp clustering for our "live" tables in the shared-nonprod project that our Dataflow jobs are populating throughout the day.

Potential benefits:

- submission_timestamp is the "natural" clustering field for these live tables. It's the only field that's likely to be limited in range for each load job
- Pocket has a use case that calls for frequent queries on just the most recent data (every 15 minutes looking at the last 15 minutes); this should make that query pattern an order of magnitude more efficient and avoid the need for a separate data store to support their near real time query needs

Potential cons:

- Increased times for load jobs

I'd like to gather some real data to prove the pros and measure the cons before advocating for this in the clustering proposal. I'd like to recreate `core_v10` as clustered and let loading run for a day in order to gather that data. `core_v10` will be interesting because it's currently our highest throughput table.

General plan of action:

- shut down the telemetry bq-sink job temporarily and let it drain
- Run a small script to unload the data from core_v10 to GCS, delete the table, recreate with clustering, load the data back in from GCS
- Reenable the bq-sink Dataflow job

Any objections or suggestions about the above plan, @relud @whd @jasonthomas ?

I'd like to potentially go ahead and do this today.

**Comment by relud** [comment]
you shouldn't unload to gcs, it will be cheaper and faster to copy it within bq

**Comment by jklukas** [comment]
> you shouldn't unload to gcs, it will be cheaper and faster to copy it within bq

Can I `bq cp` from one BQ table to another with different clustering?

Otherwise, I was trying to avoid a full scan of the data to do it as a query.

**Comment by relud** [comment]
I take it back, `bq unload` will do fine because it's under 10TB, so you don't have to use the storage api. I thought you were suggesting using the storage api to export, my bad.

**Comment by jklukas** [comment]
Working on this now.

Commands:
```
bq show --format=prettyjson --schema --project_id moz-fx-data-shar-nonprod-efed telemetry.core_v10 > corev10.bq.json
bq mk --project_id moz-fx-data-shar-nonprod-efed --schema corev10.bq.json --time_partitioning_field=submission_timestamp --clustering_fields=submission_timestamp -t telemetry.core_v20
bq extract --project_id moz-fx-data-shar-nonprod-efed --destination_format=AVRO --compression=SNAPPY telemetry.core_v10 'gs://moz-fx-data-stage-data/klukas-extract/core_v10-*.avro'
bq load --source_format=AVRO --project_id moz-fx-data-shar-nonprod-efed telemetry.core_v20 'gs://moz-fx-data-stage-data/klukas-extract/core_v10-*.avro' ~/Code/scratch/js2bq/corev10.bq.json

# Check that the tables have identical row counts, etc. then:
bq rm --project_id moz-fx-data-shar-nonprod-efed telemetry.core_v10
bq cp --project_id moz-fx-data-shar-nonprod-efed telemetry.core_v20 telemetry.core_v10

# Sanity check again, then:
bq rm --project_id moz-fx-data-shar-nonprod-efed telemetry.core_v20
```

**Comment by jklukas** [comment]
core_v10 is now partitioned; we just need to get the bq-sink job running again and then observe.

**Comment by jklukas** [comment]
Looks like this broke the Dataflow job. Each load job needs to know about the clustering, so they're failing with incompatible structure.

I'm reverting now.

**Comment by jklukas** [comment]
Full error message:

> Incompatible table partitioning specification. Expects partitioning specification interval(type:day,field:submission_timestamp) clustering(submission_timestamp), but input partitioning specification is interval(type:day,field:submission_timestamp)

I had to look at the BigQuery console at Job History > Project in order to see the detailed answer that pinned down the partitioning spec as the problem.

**Comment by jklukas** [comment]
Indeed, support for writing into clustered tables in not yet supported: https://github.com/apache/beam/pull/7061

**Comment by jklukas** [comment]
I've changed core_v10 back to a non-clustered table and I expect the job to recover and start loading core_v10 data again.

**Comment by jklukas** [comment]
The dataflow job has recovered and data is successfully being loaded into core_v10 again. Other tables were being loaded successfully throughout the incident.

**Comment by jklukas** [comment]
## Conclusion

We are blocked on using clustered tables as targets for our bq-sink jobs until https://github.com/apache/beam/pull/7061 is merged and integrated into a new Beam release. Or, until we implement a custom "Kubernetes landfill" application to handle batching files to GCS and loading to BQ.

I will proceed with my clustering proposal for now with the assumption that we can only use clustering for derived datasets.
