### ISSUE TITLE
Legacy systems bigquery table management

### ISSUE THREAD

**Issue by whd** [mozilla/gcp-ingestion#626]
/CC @robotblake 

Filing as an issue for discussion of this. Potentially this should be in the MPS repo instead, depending on how we choose to go about it.

https://github.com/mozilla/gcp-ingestion/pull/616 landed today, and tomorrow or thereabout we should have the infrastructure in place to decode these pings. However, we don't currently have a mechanism for managing the related bigquery table.

The simplest option I think would be to to add a matching json schema for stub installer as a new structured ingestion namespace. We then have our schema generator generate BQ table schemas even though the json schema for this ping wouldn't necessarily be used. A slight complication is that there is a already a namespace and JSON schema (and data!) for firefox-installer (see https://bugzilla.mozilla.org/show_bug.cgi?id=1453613) that is similar, but potentially not the same, as the actual stub installer pings. See also https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/336. If the schema being modified in https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/336 is in fact compatible with the current stub installer ping, I think we can continue to use the existing namespace and possibly json schema. It is however somewhat likely that we will want to differentiate stub installer pings from full installer pings in some way e.g. as separate BQ tables / doctypes. My guess without much investigation would be that we either copy `firefox-installer` to `stub-installer` as a namespace and update the decoder or copy `firefox-installer/install.1.json` to something like `firefox-installer/stub.1.json` to properly differentiate the two pings types. I could also be totally off-base here and this is properly handled somehow already.

Aside from the above complications, I think the notion of maintaining a json schema in a "normal" structured ingestion namespace from which a BQ table schema is automatically derived seems like the way to go here. There is only one other legacy system I'm aware of that we'll likely need to support in GCP (tls reports), which I believe has a json payload anyway (in which case, the modifications to support it should be relatively minimal and mostly be around the URI being simply `/submit/sslreports` for all pings).

**Comment by relud** [comment]
Stub installer pings are compatible with `firefox-installer/install.1.json`, and @matt-howell told me via slack that he wrote that schema to be compatible with both pings and that it would be great if stub installer pings go to the same bigquery table as full installer pings. The pings are differentiated within the table by the `installer_type` field which is either `full` or `stub`.

**Comment by whd** [comment]
Ok, I have a good understanding of the situation now. Essentially we happened to already have a compatible schema due to https://bugzilla.mozilla.org/show_bug.cgi?id=1453613 and the new decoder logic leverages this, so there is no need for a special case when managing the table. TLS reports will not need a special case WRT BQ table management, only decoding, so I'm going to close this.
