### ISSUE TITLE
`metadata.header.Date` is tricky to use in Big Query SQL

### ISSUE THREAD

**Issue by chutten** [mozilla/gcp-ingestion#631]
Hi!

  `metadata.header.Date` comes in as a string representation of the RFC 1123-conformant (well, unless someone's punking us) date in the HTTP Date header.

  BigQuery SQL doesn't make it easy to parse this... maybe there's a sequence of tokens I can pass to parse it into a datetime or timestamp, but there's just so many of them. 

  Currently I'm working around this with a JS UDF:

```sql
CREATE TEMP FUNCTION rfc1123_to_millis(x STRING)
RETURNS INT64
LANGUAGE js AS """
  return Date.parse(x);
""";
SELECT
  TIMESTAMP_MILLIS(rfc1123_to_millis(metadata.header.date)) AS meta_date
...
```

It'd be easier for me if `metadata.header.date` were already some sort of time type instead of being a string.

**Comment by jklukas** [comment]
We could consider manipulating it within the pipeline into an ISO 8601 variant that's directly loadable by BigQuery as timestamp type.

That would be the easy step, and we could still have the column be a string in BigQuery. Actually modifying the schema to have the field be a timestamp would be difficult since the schemas are already in existence. We'd also lose timezone information if we load it as a timestamp type. See https://github.com/mozilla/gcp-ingestion/issues/92

**Comment by relud** [comment]
we could do something like `metadata.header.normalized_date`

**Comment by jklukas** [comment]
Taking a step back for a moment...

It looks like the following works for parsing RFC1123 in BQ SQL without a UDF:

```
# SELECT PARSE_TIMESTAMP('%a, %d %b %Y %T %Z', 'Wed, 21 Nov 2012 23:10:20 EST')
2012-11-22 04:10:20 UTC
```

Is the above annoying? Yes. But at least resorting to a JS UDF is not necessary.

For this issue and #633, I'm beginning to think that perhaps we shouldn't make pipeline changes to manipulate these values. The raw string as it existed in the header or ping contains the most information we're going to have and I'm hesitant to throw it away or duplicate the information by providing an additional `normalized` field.

As a first step, we could provide docs on dtmo about the various timestamp formats we know are in use, which specific fields use them, and what the BigQuery invocations are to parse the timestamp and the tz.

As a second step, we could deploy persistent UDFs that codify these transformations. So you'd be able to do something like `SELECT udf.parse_rfc1123('Wed, 21 Nov 2012 23:10:20 EST')`. That would be easier to remember come analysis time.

The person issuing queries still has to know that docs or UDFs exist, so it's not as convenient as a field already converted to a TIMESTAMP or compatible string, but seems like a less heavyweight and more adaptable overall approach than trying to support a potentially growing number of timestamp translations in the pipeline.

**Comment by jklukas** [comment]
Heck we could probably create a general `udf.parse_timestamp` that's a `COALESCE` of various `PARSE_TIMESTAMP` invocations, so that you really only need to know about one udf for exploratory analysis and you don't have to worry about figuring out which format a given field is in.

**Comment by jklukas** [comment]
Here's a working example of how we might provide this sort of logic in a view:

```
CREATE TEMPORARY FUNCTION
  udf_normalize_metadata(metadata ANY TYPE) AS ((
    SELECT
      AS STRUCT metadata.* REPLACE ( (
        SELECT
          AS STRUCT metadata.header.*,
          PARSE_TIMESTAMP('%a, %d %b %Y %T %Z', metadata.header.date) AS normalized_date) AS header )) );
  --
SELECT
  * REPLACE(udf_normalize_metadata(metadata) AS metadata)
FROM
  `moz-fx-data-shar-nonprod-efed.telemetry_live.main_v4`
WHERE
  DATE(submission_timestamp) = "2019-08-04"
  AND metadata.header.date IS NOT NULL
LIMIT
  10
```

We would modify the user-facing `main` view to include the `REPLACE(udf_normalize_metadata(metadata) AS metadata)` clause.

**Comment by jklukas** [comment]
We have now added a field `metadata.header.parsed_date` to the `telemetry.core` view as part of https://github.com/mozilla/bigquery-etl/pull/546. We need to update the schema pipeline code to get this rolled out for the other doctypes like `main`.
