### ISSUE TITLE
Convert main_summary_v4 to clustered

### ISSUE THREAD

**Issue by jklukas** [mozilla/gcp-ingestion#632]
I was just working with a colleague on a Colab notebook and saw that they had an exploratory query to see the structure of main_summary that was scanning 300 TB of data.

I think we should convert main_summary to clustered on sample_id ASAP so that we greatly reduce the possibility of this continuing to happen. Queries with a LIMIT clause will scan much less data.

**Comment by relud** [comment]
fixed in [bug 1567025](https://bugzilla.mozilla.org/show_bug.cgi?id=1567025)
