### ISSUE TITLE
Convert datetime/timestamp from permissive ISO8601 to BigQuery-supported subset RFC3339 

### ISSUE THREAD

**Issue by chutten** [mozilla/gcp-ingestion#633]
Glean's `ping_info.end_time` is an ISO8601 datetime which doesn't have (or need, to be conformant) a "seconds" part to the timestamp. Unfortunately BigQuery only supports the more restrictive RFC3339 standard.

Could we, at ingestion, convert ISO8601 to RFC3339 for ease of analysis? Might be one step closer to translating directly to higher level types in the data representation itself.

**Comment by jklukas** [comment]
Is it an option to update the Glean libraries to emit RFC3339-compliant values? I assume that would break other things, but if not, that would be an easier to understand path to ease of timestamp analysis.

**Comment by Dexterp37** [comment]
> 
> Is it an option to update the Glean libraries to emit RFC3339-compliant values? I assume that would break other things, but if not, that would be an easier to understand path to ease of timestamp analysis.

I'd rather not to, unless there's a strict reason to overfit to GCP for this. Data collection already begun with the ISO8601 format, in 2 weeks Fenix Preview will start sending data and analysts will begin to ... well, do analyses :)

In general, I'd rather not change something on the SDK side to accommodate a specific pipeline vendor, unless there's no other technical solution or the only solutions are engineering nightmares.

**Comment by jklukas** [comment]
Are there other places where we're using ISO8601 timestamps without seconds?

I'm trying to get a sense of the scope of the problem. Is this a one-off modification we would need to make for this particular field, or would we want a method for specifying a list of expected fields in this format?

> In general, I'd rather not change something on the SDK side to accommodate a specific pipeline vendor

I respect that position, although I do overall get the impression that RFC3339 is more common and generally better supported out-of-the-box by datetime parsing libraries such that this feels less like a vendor-specific accommodation and more like an optimization for best chance of portability across environments. Again, this is an impression and I don't have ready data to back that up.

**Comment by Dexterp37** [comment]
> 
> 
> Are there other places where we're using ISO8601 timestamps without seconds?
> 
> I'm trying to get a sense of the scope of the problem. Is this a one-off modification we would need to make for this particular field, or would we want a method for specifying a list of expected fields in this format?

Glean SDK `datetime` is generally for use by all products using the SDK. Right now, Fenix doesn't send any custom metric of that type, but it doesn't mean it won't. The pipeline knows or can know all the metadata associated with this and other data points: the metric `type` comes from the schema, the resolution for the `datetime type` (and so the parsing pattern) comes from the `probe-scraper`, which is already used for the schema generator.

We might even send just dates without time, not just without seconds.

> > In general, I'd rather not change something on the SDK side to accommodate a specific pipeline vendor
> 
> I respect that position, although I do overall get the impression that RFC3339 is more common and generally better supported out-of-the-box by datetime parsing libraries such that this feels less like a vendor-specific accommodation and more like an optimization for best chance of portability across environments. Again, this is an impression and I don't have ready data to back that up.

Maybe :) We can evaluate this for the future, but I'd be hesitant to change something so fundamental right now, given that code freeze is approaching :)

**Comment by jklukas** [comment]
See https://github.com/mozilla/gcp-ingestion/issues/631#issuecomment-497749115 for a proposal that we handle this through documentation and perhaps UDFs rather than changing values in the pipeline.

**Comment by fbertsch** [comment]
I think the resolution of this does lie in UDFs and views. Let's plan on the following:

1. Create a UDF to parse the ISO8601 string, as is being discussed in #631 
2. Create a view that is _exactly_ the original table, but with all the string datetimes represented as timestamps/datetimes.

The immediate need of analysis will be filled by (1.). I imagine it will take longer to get the views up-and-running, but luckily it is non-blocking (data is available), and totally backwards compatible (and no backfill required).

**Comment by jklukas** [comment]
I'm beginning to feel like we have a need for automated creation of views on top of raw tables. That job could know about things like the formats of various timestamps in order to fill needs like (2) that @fbertsch describes. Perhaps that could be wrapped up as part of the periodic schema update job.

**Comment by relud** [comment]
see also #640 for a more general discussion of decoder type transformation

**Comment by jklukas** [comment]
Example of how we might define a UDF to be used in views over glean pings to provide normalized fields like this:

```
CREATE TEMPORARY FUNCTION
  udf_normalize_ping_info(ping_info ANY TYPE) AS ((
    SELECT
      AS STRUCT 
        ping_info.*, 
        PARSE_TIMESTAMP('%FT%H:%M%Ez', ping_info.start_time) AS normalized_start_time));
  --
SELECT
  * REPLACE(udf_normalize_ping_info(ping_info) AS ping_info)
FROM
  `moz-fx-data-shared-prod.org_mozilla_fenix_stable.baseline_v1`
WHERE
  DATE(submission_timestamp) = "2019-08-04"
  AND metadata.header.date IS NOT NULL
LIMIT
  10
```

**Comment by jklukas** [comment]
Note that we now have user-facing views in place such that we can start adding custom parsed fields as needed. It's not an immediate priority, but I expect us to add a fields for parsed glean timestamps by EOH2 if not sooner.

**Comment by jklukas** [comment]
All user-facing views on Glean pings now have parsed start_time and end_time fields available.
