### ISSUE TITLE
Add option to not fill `additionalProperties` for specific schemas/docTypes

### ISSUE THREAD

**Issue by fbertsch** [mozilla/gcp-ingestion#644]
Specifically, we are looking at the main ping. To use table splitting, each table will be "missing" parts of the schema. We want these dropped instead of filled.

Short term, we can have a small main-ping schema, which includes the environment and common ping sections.  We would prefer this be used without additionalProperties as well, to reduce storage cost.

**Comment by jklukas** [comment]
A few options here:

- hard-code an exemption for main pings
- introduce a runtime parameter (`bqDropAdditionalPropertiesForDocTypes`?) for the BQ sink that accepts a comma-separated list of doctypes for which to skip additionalProperties accumulation
- split out main pings to a separate pubsub topic and have a separate bq sink job for them

I'm inclined to pursue the second of these options.

**Comment by mreid-moz** [comment]
>     * introduce a runtime parameter (`bqDropAdditionalPropertiesForDocTypes`?) for the BQ sink that accepts a comma-separated list of doctypes for which to skip additionalProperties accumulation

I've been thinking of this as "strict" mode if that helps for naming - you get exactly what's specified in the schema and nothing more.

**Comment by jklukas** [comment]
I'll go with `bqStrictSchemaDocTypes`.

**Comment by whd** [comment]
Worth noting I totally forgot about https://github.com/mozilla/gcp-ingestion/blob/master/docs/pain_points.md#templates and as such when this went out it failed miserably. Adding the configuration at template compile time has resolved the issue.

**Comment by jklukas** [comment]
I'd be interested to see what exactly the error was, since the NestedValueProvider problem I thought only applied to PubsubIO.Write. I will try to look into that tomorrow.

**Comment by whd** [comment]
@jklukas for your consideration, such an error can be found at gs://moz-fx-data-stage-data/structured-decoded_bq-sink/error/2019-06-13/23/error-2019-06-13T23:20:00.000Z-2019-06-13T23:30:00.000Z-00059-of-00060.ndjson.gz

"error_message":"java.lang.RuntimeException: Unable to load runtime value."
