### ISSUE TITLE
telemetry.mobile_metrics_v1 bq sink runtime failure

### ISSUE THREAD

**Issue by whd** [mozilla/gcp-ingestion#649]
[GCP console link](https://console.cloud.google.com/errors/CLnK6YSOtru4rQE?time=P1D&project=moz-fx-data-beam-nonprod-b5f4&organizationId=442341870013)

Error while reading data, error message: JSON parsing error in row starting at position 2312109: Array specified for non-repeated field: metrics.value.

**Comment by jklukas** [comment]
A payload in question looks like:

```
{"submission_timestamp":"2019-06-07T01:35:55.676507Z","normalized_os":"Android","sample_id":11,"normalized_country_code":"SA","normalized_channel":"release","normalized_app_name":"Focus","document_id":"5a96bd97-4962-4492-868a-511032555acc","normalized_os_version":"26","clientId":"a75bd6a7-2fdd-4079-839a-b8885f5d7952","os":"Android","tz":180,"createdTimestamp":1559871320138,"locale":"ar-SA","createdDate":"2019-06-07","v":1,"profileDate":17722,"arch":"arm64-v8a","metrics":[{"key":"scalars","value":[{"key":"parent","value":"{\"telemetry.persistence_timer_hit_count\":6}"},{"key":"content","value":"{\"telemetry.discarded.scalar_actions\":0,\"memoryreporter.max_ghost_windows\":0,\"telemetry.discarded.keyed_scalar_actions\":0,\"telemetry.discarded.accumulations\":0,\"telemetry.discarded.keyed_accumulations\":0,\"telemetry.discarded.child_events\":0}"}]},{"key":"keyedHistograms","value":[]},{"key":"histograms","value":[]},{"key":"keyedScalars","value":[]}],"osversion":"26","device":"HUAWEI-BND-L21","seq":66,"metadata":{"geo":{"db_version":"2019-06-03T11:45:05Z","country":"SA","city":"Dammam","subdivision1":"04"},"header":{"date":"Fri, 07 Jun 2019 01:35:53 GMT+00:00"},"document_namespace":"telemetry","document_version":"1","uri":{"app_name":"Focus","app_version":"6.2","app_build_id":"121871204-GeckoView","app_update_channel":"release","uri":"/submit/telemetry/5a96bd97-4962-4492-868a-511032555acc/mobile-metrics/Focus/6.2/release/121871204-GeckoView"},"user_agent":{"os":"Android"},"document_type":"mobile-metrics"}
```

See gs://moz-fx-data-stage-dataflow/bqsink/201905280941_c2738fd/tmp/BigQueryWriteTemp/beam_load_sink00528164328dfd3f3be_5b69ef654107461c95f211fe175c4d71/1e2cd681-a99d-441d-9bdf-29e5d2faff64

In there, the "metrics" repeated field indeed contains "value" instances that are arrays. This could be a problem with the transformation logic in the bq sink.

**Comment by jklukas** [comment]
It looks like the structure has gotten inverted. It should be `metrics.<process>.scalars...` but it's appearing as `metrics.scalars.<process>...`

**Comment by jklukas** [comment]
I've tracked this down to a problem with the translation in PubSubMessageToTableRow rather than the schema transpiler. The bq sink job doesn't correctly handle nested repeated structs. Working on it.
