### ISSUE TITLE
Hitting API rate limit in BQ sink

### ISSUE THREAD

**Issue by jklukas** [mozilla/gcp-ingestion#651]
We have at least one message going to error output due to:

> "error_message":"com.google.common.util.concurrent.UncheckedExecutionException: com.google.cloud.bigquery.BigQueryException: Exceeded rate limits: too many api requests per user per method for this user_method. For more information, see https://cloud.google.com/bigquery/troubleshooting-errors"

> "stack_trace":"[com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051), com.google.common.cache.LocalCache.get(LocalCache.java:3953), com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4873), com.mozilla.telemetry.transforms.PubsubMessageToTableRow.processElement(PubsubMessageToTableRow.java:139), com.mozilla.telemetry.transforms.PubsubMessageToTableRow.processElement(PubsubMessageToTableRow.java:57), com.mozilla.telemetry.transforms.MapElementsWithErrors$DoFnWithErrors.processElementOrError(MapElementsWithErrors.java:88), com.mozilla.telemetry.transforms.MapElementsWithErrors$DoFnWithErrors$DoFnInvoker.invokeProcessElement(Unknown Source), org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:213), org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.processElement(SimpleDoFnRunner.java:178), org.apache.beam.runners.dataflow.worker.SimpleParDoFn.processEleme..."

See gs://moz-fx-data-stage-data/telemetry-decoded_bq-sink/error/2019-06-08/13/error-2019-06-08T14:00:00.000Z-2019-06-08T14:10:00.000Z-0-00041-of-00060.ndjson.gz

I'm pretty sure this is due to us hitting the endpoint for describing tables, which we use to reference BQ schemas when transforming messages to TableRow objects. We cache the value of the call, but we may not be caching aggressively enough or this may be due to startup where we have to hit the same endpoint for a number of tables.

We perhaps need to add in some logic to detect the exception and hold off.

I will open a support case with Google to confirm this is the limit we're hitting.

**Comment by jklukas** [comment]
I'm not going to open a case with Google, since I'm fairly certain I understand exactly what limit we're hitting now.

**Comment by whd** [comment]
I'm going to re-open this as the latest code still appears to be generating this error, see e.g.

gs://moz-fx-data-stage-data/structured-decoded_bq-sink/error/2019-06-13/23/error-2019-06-13T23:30:00.000Z-2019-06-13T23:40:00.000Z-0-00027-of-00060.ndjson.gz

**Comment by jklukas** [comment]
https://github.com/mozilla/gcp-ingestion/pull/678 should allow us to close this, but to use the new code path, we need to configure the bq sink jobs to reference the schemas tarball file.

We'll need to set `schemasLocation` and `schemaAliasesLocation`; these can point to the same locations we use for the decoder jobs. It looks like perhaps we don't set the aliases for the decoder, at least in prod. We can start with providing just the schemasLocation and then deal with figuring out if aliases are needed as a separate step.
