### ISSUE TITLE
Consider adding a document id derived from pubsub message id for pings without a document id

### ISSUE THREAD

**Issue by whd** [mozilla/gcp-ingestion#668]
The legacy systems we ingest from (sslreports, stub installer) don't necessarily provide a document id. We could add an arbitrary one in the decoder but the pubsub message id (or in ingestion edge) would provide a more stable value since it will be unique and persisted to durable storage in case of reprocessing. We want the document id to be a UUID; presumably there is some casting that would be required for this.

**Comment by jklukas** [comment]
One of the recent versions of Beam added messageId to the PubSubMessage class and we had to avoid serializing it in order to keep our tests from breaking.

But I'm pretty sure we'll still have the messageId available when reading from PubSub. Anyways, this sounds doable. We might just have to be careful about where we put it and we'll likely have to refactor some tests.

**Comment by jklukas** [comment]
See our [`PubsubMessageMixin`](https://github.com/mozilla/gcp-ingestion/blob/master/ingestion-beam/src/main/java/com/mozilla/telemetry/util/Json.java#L221-L234) to see how we avoid serializing `messageId`. We'd need to remove the alteration of `messageId` or somehow make that optional for tests. We might need to add a transform for optionally nulling messageIds and add a pipeline option to make that configurable.

**Comment by jklukas** [comment]
See [StubUri](https://github.com/mozilla/gcp-ingestion/blob/master/ingestion-beam/src/main/java/com/mozilla/telemetry/decoder/ParseUri.java#L101-L103) in ParsePayload for an example of handling a legacy system. Maybe we add handling there for converting a pubsub messageId into a docId and explicitly drop messageId there. I suppose we already do drop messageId considering we return a value where we use the `PubsubMessage` constructor without a messageId parameter.
