### ISSUE TITLE
Make deduplication step optional for Republisher

### ISSUE THREAD

**Issue by whd** [mozilla/gcp-ingestion#669]
For certain use cases (e.g. republishing raw data from prod to stage) we don't want to use the deduplication facility.

@relud mentioned that in the current implementation documents without a document id might currently throw errors. We should probably ignore deduplication in this case (or see #668 for making sure all documents have document ids).

**Comment by jklukas** [comment]
> in the current implementation documents without a document id might currently throw errors

I don't think this is true. Documents that have a `document_id` attribute that is not a valid UUID will throw IllegalArgumentException and go to error output. But if no attribute is present, the message should pass through without contacting Redis.
