### ISSUE TITLE
Field names in `additional_properties` are snake_cased

### ISSUE THREAD

**Issue by acmiyaguchi** [mozilla/gcp-ingestion#711]
The field names of the additional properties are normalized by snake_casing when ingesting into BigQuery. While this makes the fields consistent with the rest of the table, this makes it difficult to update the source schemas. I expected the behavior to match the casing of the source data, so we can reduce the size of additional properties over time.

---

To motivate this, I'm looking into updating the main ping schema to include the `payload.info` section.

I wrote a query along the following lines:

```SQL
SELECT
  JSON_EXTRACT(additional_properties,
    "$.payload.info") AS info
FROM
  telemetry_live.main_v4
WHERE
  submission_timestamp >= timestamp '2019-07-23'
  AND submission_timestamp < timestamp '2019-07-24'
```

followed by:

```SQL
CREATE TEMP FUNCTION
  udf_types_js (input STRING)
  RETURNS ARRAY<STRUCT<key STRING,
  value STRING,
  type STRING>>
  LANGUAGE js AS """
    if (input == null) {
      return null;
    }
    result = [];
    let parsed = JSON.parse(input);
    for (let key in parsed) {
      result.push({"key": key, "value": parsed[key], "type": typeof parsed[key]});
    }
    return result;
    """;
WITH
  extracted AS (
  SELECT
    info.*
  FROM
    `amiyaguchi-dev.testing.payload_info`,
    UNNEST(udf_types_js(info)) AS info )
SELECT
  key, type, count(*) as freq
FROM
  extracted
group by 1, 2
order by 1, 2
```

and got results as follows:

Row | key | type | freq |  
-- | -- | -- | -- | --
1 | addons | boolean | 11 |  
2 | addons | string | 275656290 |  
3 | async_plugin_init | boolean | 24239158 |  
4 | flash_version | string | 154062600 |  
5 | previous_build_id | number | 3 |  
6 | previous_build_id | object | 245218834 |  
7 | previous_build_id | string | 31088744 |  
8 | previous_session_id | object | 1970803 |  
9 | previous_session_id | string | 274317059 |  
10 | previous_subsession_id | object | 1279342 |  
11 | previous_subsession_id | string | 275028239 |  
12 | profile_subsession_counter | number | 276307581 |  
13 | reason | string | 276307581 |  
14 | revision | string | 276307581 |  
15 | session_id | string | 276307581 |  
16 | session_length | number | 276254629 |  
17 | session_length | object | 135 |  
18 | session_start_date | string | 276307581 |  
19 | subsesshon_counter | number | 3 |  
20 | subsession_counter | number | 276307578 |  
21 | subsession_id | string | 276307575 |  
22 | subsession_start_date | string | 276307581 |  
23 | timezone_offset | number | 276307580 |  
24 | timezone_offset | object | 1 | 

However, matching this up the the [firefox source docs](https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/telemetry/data/main-ping.html), I noticed that the names have been snake cased. In this particular case, it looks like `async_plugin_init` might be useful to add to the schema, but what is the original casing?

This affects other properties that we may want to add to the schemas, such as simple measures or user preferences.

**Comment by acmiyaguchi** [comment]
I'll note that it's possible to add the field to the JSON Schema and have it correctly show up in the BigQuery schema if`--normalize-casing` is set or `snake_casing` happens to be the correct casing. This behavior is not well defined though and will not validate against pings from the edge.

**Comment by jklukas** [comment]
My gut also says this is the right thing to do. I'm looking into it.
