### ISSUE TITLE
mvn fails when run from the top level

### ISSUE THREAD

**Issue by jklukas** [mozilla/gcp-ingestion#729]
@wlach reports that he ran into several different failures when trying to onboard on this project. We eventually realized that he was running the top-level `bin/mvn` script which we hadn't really exercised.

We should make sure that it's possible to run mvn at the top level and correctly build/test the sub-projects.

**Comment by jklukas** [comment]
Also, it's not clear that you run some scripts to download files before being able to successfully execute tests.

**Comment by relud** [comment]
running this from the git root works, but note that it requires `-pl ingestion-beam` to not run the exec plugin for all modules, including the parent:

```bash
echo '{"attributeMap":{"remote_addr":"63.245.208.195"},"payload":"dGVzdA=="}' > input.json
./bin/mvn -pl ingestion-beam exec:java -Dexec.args="--input=input.json --inputType=file --outputType=stdout --errorOutputType=stderr"
```

running `./bin/mvn test` from the root also works fine for me when i have the dependencies downloaded

**Comment by relud** [comment]
I believe this is working now
