### ISSUE TITLE
Validate payload_bytes_decoded output

### ISSUE THREAD

**Issue by jklukas** [mozilla/gcp-ingestion#733]
I am taking a look at data from the weekend (2019-08-10 and 2019-08-11) when we should have had a stable pipeline running using streaming inserts to BQ for payload_bytes_* tables.

I am seeing a very minimal difference in counts, with a total of 7 more pings in payload_bytes_decoded compared to live tables across all telemetry doctypes:

```
WITH
  pbytes AS (
  SELECT
    DATE(submission_timestamp) AS submission_date,
    _TABLE_SUFFIX AS tbl,
    COUNT(*) AS pbytes_n
  FROM
    `moz-fx-data-shar-nonprod-efed.payload_bytes_decoded.telemetry_telemetry__*`
  WHERE
    DATE(submission_timestamp) BETWEEN "2019-08-10"
    AND "2019-08-11"
  GROUP BY
    1,
    2
  ORDER BY
    1,
    2 ),
  --
  live AS (
  SELECT
    DATE(submission_timestamp) AS submission_date,
    _TABLE_SUFFIX AS tbl,
    COUNT(*) AS live_n
  FROM
    `moz-fx-data-shar-nonprod-efed.telemetry_live.*`
  WHERE
    DATE(submission_timestamp) BETWEEN "2019-08-10"
    AND "2019-08-11"
  GROUP BY
    1,
    2
  ORDER BY
    1,
    2 )
  --
SELECT
  *,
  pbytes_n - live_n AS diff
FROM
  pbytes
FULL JOIN
  live
USING
  (submission_date,
    tbl)
WHERE pbytes_n - live_n != 0
ORDER BY
  5 DESC,
  2,
  1
```

Row | submission_date | tbl | pbytes_n | live_n | diff
-- | -- | -- | -- | -- | --
1 | 2019-08-10 | crash_v4 | 1659106 | 1659103 | 3 |  
2 | 2019-08-11 | crash_v4 | 1495234 | 1495231 | 3 |  
3 | 2019-08-10 | core_v10 | 60359479 | 60359478 | 1

If I change the count to be over distinct document_ids, the `core_v10` difference goes away, but we still see 3 crash pings on each of the two days that didn't make it to the live tables. I'm not particularly concerned about that difference, but we can investigate further if needed.

**Comment by jklukas** [comment]
cc @relud @whd

**Comment by jklukas** [comment]
I'm looking at crash ping errors via:

```
CREATE TEMP FUNCTION
  udf_js_gunzip (input BYTES)
  RETURNS STRING
  LANGUAGE js AS """
    // converts a byte array to a string
    function binary2String(byteArray) {
        return String.fromCharCode.apply(String, byteArray);
    }
    
    // input is in base64, so it needs to be decoded
    var decodedData = atob(input);
    var compressedData = decodedData.split('').map(function(e) {
        return e.charCodeAt(0);
    });
    
    try {
      var gunzip = new Zlib.Gunzip(compressedData); 
    
      // decompress returns bytes that need to be converted into a string
      var unzipped = gunzip.decompress();
      return binary2String(unzipped);
    } catch (err) {
    try {
      return binary2String(input);
      } catch (err) {
      return null;
      }
    }
"""
OPTIONS
  ( library = "gs://bigquery-wasm-dev/gunzip.min.js",
    library = "gs://bigquery-wasm-dev/atob.js" );
    --
SELECT
  exception_class, 
  --count(*),
  payload,
  udf_js_gunzip(payload)
FROM
  `moz-fx-data-shar-nonprod-efed.payload_bytes_error.telemetry`
WHERE
  DATE(submission_timestamp) = "2019-08-10"
  AND uri like '%/crash/%'
  AND exception_class not in ('com.mozilla.telemetry.decoder.Deduplicate$DuplicateIdException', 'org.everit.json.schema.ValidationException')
  --group by 1 order by 2 desc
LIMIT
  1000
```

Besides duplicates and validation errors and json parse exceptions, the largest error stream is IOExceptions where the payload is "H4sIAAAAAAAAAAMAAAAAAAAAAAA=" which corresponds to the empty string, gzipped and base64-encoded.

**Comment by jklukas** [comment]
There are no error messages logged to GCS for 2019-08-10 or 2019-08-11:

```
$ gsutil ls gs://moz-fx-data-stage-data/telemetry-decoded_bq-sink-raw/error/
gs://moz-fx-data-stage-data/telemetry-decoded_bq-sink-raw/error/2019-08-01/
gs://moz-fx-data-stage-data/telemetry-decoded_bq-sink-raw/error/2019-08-02/
gs://moz-fx-data-stage-data/telemetry-decoded_bq-sink-raw/error/2019-08-05/
gs://moz-fx-data-stage-data/telemetry-decoded_bq-sink-raw/error/2019-08-09/
gs://moz-fx-data-stage-data/telemetry-decoded_bq-sink-raw/error/2019-08-12/
```

But today and on Friday, I'm seeing UncheckedExecutionExceptions being raised due to hitting BQ API rate limits for some limited periods of time. These may be correlated to deploys, I'm not sure. But we thought this error case was removed after moving to schema files rather than hitting the BQ API for schemas.

**Comment by whd** [comment]
There haven't been any deploys today, but there is probably increased load relative to Friday due to general browser usage patterns. Friday could definitely be tied to deploys since I was tuning a lot of parameters.
