### ISSUE TITLE
BQ sink (with schemas, decoded) failure to make progress

### ISSUE THREAD

**Issue by whd** [mozilla/gcp-ingestion#739]
[Job](https://console.cloud.google.com/dataflow/jobsDetail/locations/us-west1/jobs/2019-08-09_15_48_44-13469249664244951147?project=moz-fx-data-beam-nonprod-b5f4)
[Logs](https://console.cloud.google.com/logs/viewer?resource=dataflow_step%2Fjob_id%2F2019-08-09_15_48_44-13469249664244951147&logName=projects%2Fmoz-fx-data-beam-nonprod-b5f4%2Flogs%2Fdataflow.googleapis.com%252Fworker&interval=NO_LIMIT&project=moz-fx-data-beam-nonprod-b5f4&minLogLevel=500&expandAll=false&timestamp=2019-08-13T17:18:03.907000000Z&customFacets=&limitCustomFacetWidth=true&scrollTimestamp=2019-08-13T14:29:59.312000000Z)

Around the time progress stops (9am Pacific) I see "Shutting down JVM after 8 consecutive periods of measured GC thrashing. Memory is used/total/max = 9819/11025/11025 MB, GC last/max = 99.84/99.84 %, #pushbacks=11, gc thrashing=true. Heap dump not written.". Notably the job isn't autoscaling up in response to the increasing latency metrics.

This is with the standard BQ sink configuration (SSDs, higher mem instances, only specific docTypes being streamed) which has been our most stable configuration so far, so this is somewhat concerning.

**Comment by relud** [comment]
I believe this has been resolved, @whd feel free to reopen if this still needs investigation
