### ISSUE TITLE
Write tests for local IO in ingestion-beam's Sink pipeline

### ISSUE THREAD

**Issue by relud** [mozilla/gcp-ingestion#74]
specifically we should test

- [x] `--inputType=file`
- [x] `--outputType=`
   - [x] `file`
   - [x] `stdout`
   - [ ] `stderr`
- [x] `--errorOutputType=`
   - [x] `file`
   - [ ] `stdout`
   - [ ] `stderr`

using local file paths, ideally with junit tests.

**Comment by jklukas** [comment]
Is there any reason to do extensive testing of stdout and stderr outputs? Do we expect to ever have use cases for those, or are they simply for testing?

#54 is relevant here. I may have time early next week to start working on a Hamcrest matcher for comparing files without regard to message order.

**Comment by relud** [comment]
we should focus on testing produse cases, so not stdout/stderr. we should add a warning when they are selected to tell people when they use a component that is not considered not prod quality.

**Comment by jklukas** [comment]
See https://github.com/mozilla/gcp-ingestion/pull/97 which introduces utilities for doing this sort of testing on top of junit.

**Comment by jklukas** [comment]
Closing this, as we have tests that exercise stdout and local file output for main output and error output.
