### ISSUE TITLE
BQ sink efficiency: Delay conversion of compressed payloads to TableRows

### ISSUE THREAD

**Issue by jklukas** [mozilla/gcp-ingestion#742]
The [BigQueryIO docs](https://beam.apache.org/releases/javadoc/2.14.0/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIO.html) state that it's recommended to provide a function to convert your payloads to TableRow rather than converting to TableRow and passing that collection into BigQueryIO.Write directly. The docs say nothing about why this is inefficient, but some digging through the code suggests that the efficiency boost comes from being able to delay the conversion until after some grouping has happened.

So, we could get a potentially large I/O efficiency boost by leaving payloads compressed and refactoring `PubSubMessageToTableRow` so that we instead put that logic in a function that handles uncompressing a payload and converting to TableRow immediately before the data is written to objects in GCS.

This has the disadvantage of reduced error handling, but I believe the only case that we _want_ to be able to handle for sending payloads to error output is if the destination table doesn't exist. We should still be able to handle that part separately based on attributes. We do not expect the code that transforms PubSubMessage payloads to TableRow to throw exceptions, so it's likely a good thing if they end up causing the pipeline to fail.

**Comment by jklukas** [comment]
To summarize, I believe we'd get a significant I/O efficiency boost because the checkpointed state that BigQueryIO has to write to disk would be gzipped, so potentially ~10x smaller. Only in the final stage of writing objects to GCS would the payloads be written uncompressed. I think. Potentially.

**Comment by whd** [comment]
This definitely seems worthy of investigation.


> This has the disadvantage of reduced error handling, but I believe the only case that we _want_ to be able to handle for sending payloads to error output is if the destination table doesn't exist. We should still be able to handle that part separately based on attributes. We do not expect the code that transforms PubSubMessage payloads to TableRow to throw exceptions, so it's likely a good thing if they end up causing the pipeline to fail.

This sounds accurate to me.

**Comment by jklukas** [comment]
cc @relud 
I may work on this tomorrow.
