### ISSUE TITLE
Issues routing beam errors to pubsub

### ISSUE THREAD

**Issue by whd** [mozilla/gcp-ingestion#756]
As I started implementing this I ran into some issues. The current beam job error messages have no identifiers to use to label messages i.e. the error messages themselves don't contain information like "this is the raw bq sink for telemetry". The errorOutput configuration of the beam job (currently, a GCS prefix) is where this information is conveyed. I was planning on creating a single ops pubsub topic for beam jobs and a single bigquery dataset/table to output them to, but that topology loses all job identifiers for messages. We could instead have multiple destination tables, one for each job type, but that still has the problem that the bq sink writing them to errors has no attributes to route them with. We could send error output directly to each job-specific errors BQ table without pubsub, but then we don't have the ability to use these error rates in e.g. CEP monitoring which was one of the motivating factors for this change. We could have a pubsub topic / output sink for each job type but that's just gross. We could insert extra attributes into the messages themselves for routing purposes, but that probably has separate concerns.

I've decided not to block the production deployment on this change since it's an operational one that is somewhat unrelated to pipeline efficacy (but is important for validation). I would like opinions on how we should best proceed to make the dataflow error output as useful as possible.

**Comment by jklukas** [comment]
In terms of what's easy to implement, my immediate thought is that we could add the value of the `input` option as an attribute, which would record which pubsub topic was being read. This would give us something like 

    "input": "projects/moz-fx-data-beam-nonprod-b5f4/subscriptions/telemetry-decoded.bq-sink"

in the attributeMap, and we'd add `input` as a STRING field in the BQ table.

Input topic name is basically a proxy for pipeline family name and follows a similar naming convention. We could parse the pipeline family out of the input topic name and emit a `pipeline_family` attribute instead; I'd prefer to avoid adding that complexity to handling errors, but it may be worthwhile for sanity when using the data downstream.

**Comment by jklukas** [comment]
I'm going to work on a PR for adding `input` and `job_name` and potentially `pipeline_family` as attributes when writing out error messages.

**Comment by jklukas** [comment]
See linked PRs for MPS and gcp-ingestion to add `input`, `job_name`, and `input_type`. Merging these, you'd be able to filter errors to just the `structured` pipeline family by doing `WHERE job_name LIKE 'structured-%'`
