### ISSUE TITLE
Delete partial day 2019-08-21 from _stable tables

### ISSUE THREAD

**Issue by jklukas** [mozilla/gcp-ingestion#773]
We did a full prod deploy of gcp-ingestion near the end of the day UTC on 2019-08-21, and then the `copy_deduplicate` jobs ran, copying this partial day into `_stable` tables. We should do a one-time deletion of those partial partitions, making sure not to remove data for long-running prod namespaces that received a full day (activity-stream and fenix).

cc @whd 

This will require ops-level permissions.

**Comment by whd** [comment]
r? https://gist.github.com/whd/af2b687b0dd511d30deb5fb60cc49c9f

**Comment by whd** [comment]
:+1: to the efficiency suggestion. `fenix_nightly` was not deployed to prod (it was not even deployed to stage until the second round of validation occurred). I'll run this momentarily.

**Comment by whd** [comment]
Gist updated and run completed.
