### ISSUE TITLE
Unexplained partial deduplication between raw decoded and live tables

### ISSUE THREAD

**Issue by jklukas** [mozilla/gcp-ingestion#775]
See https://docs.google.com/document/d/14UoZGAI2CgMQW4qeXIX5Bj9nq2kvfCUaONiNknXXxYE/edit#heading=h.co8fhr5wmnov

We don't understand why we end up with slightly lower counts in live tables compared to the equivalent decoded bytes tables, but we do know that the missing messages are all duplicates. This seems to indicate that either that raw decoded sink is sometimes writing records twice or that the sink writing to live tables is sometimes deduplicating messages.

We should understand how this happens.

**Comment by jklukas** [comment]
If I count based on distinct (document_id, submission_timestamp), live tables and decoded bytes match exactly:

```
WITH live AS (
SELECT _TABLE_SUFFIX AS tbl, COUNT(distinct concat(document_id, string(submission_timestamp))) AS n
FROM `moz-fx-data-shared-prod.telemetry_live.*`
WHERE DATE(submission_timestamp) = "2019-08-22"
GROUP BY 1 ORDER BY 2 DESC
),

decoded AS (
SELECT _TABLE_SUFFIX AS tbl, COUNT(distinct concat(document_id, string(submission_timestamp))) AS n
FROM `moz-fx-data-shared-prod.payload_bytes_decoded.telemetry_telemetry__*`
WHERE DATE(submission_timestamp) = "2019-08-22"
GROUP BY 1 ORDER BY 2 DESC
),

diff AS (
SELECT tbl, l.n AS live, d.n AS decoded, d.n - l.n AS diff FROM live AS l
FULL JOIN decoded AS d
USING (tbl)
)

SELECT * FROM diff order by diff DESC
```

The only difference we see in counts is for sync pings, where we understand there were failures due to large payloads.

So, these are not messages sent multiple times by clients, but rather messages that have already hit the pipeline and are getting duplicated. That seems to support the idea that the payload bytes sink sometimes double-publishes.

**Comment by jklukas** [comment]
One thing I find odd is that the telemetry `bq-sink-raw` that populates payload bytes tables is using more resources in steady state (25 workers vs. 17) and throwing more errors (77 "Processing stuck" errors vs. 5) compared to the `bq-sink` that populates the live tables.

One would think that the job populating live tables has significantly more work to do: uncompressing the payload, parsing the json, modifying, and then recompressing.

One thought is that perhaps leaking of duplicate records is related to bundle retries in error scenarios, so the more error prone raw sink is introducing dupes at a higher rate.

**Comment by relud** [comment]
could this be related to streaming vs file loads?

**Comment by jklukas** [comment]
> could this be related to streaming vs file loads? or perhaps including document_id as insertId?

That's a good call to check. I don't believe either of these pipelines is doing any streaming inserts. I just checked the configuration in the UI and they're both set to "mixed" mode with `bqStreamingDocTypes=[activity-stream/impression-stats, activity-stream/spoc_fills, mobile/activation]`

**Comment by relud** [comment]
the sink for everything but live tables is now running on `ingestion-sink` instead of `ingestion-beam`, and we have confirmed we are getting at-least-once delivery behavior from `ingestion-sink`.
