### ISSUE TITLE
Non-ASCII text being redacted in the pipeline

### ISSUE THREAD

**Issue by jklukas** [mozilla/gcp-ingestion#780]
@tdsmith found that description values for Mozilla Online addons in BQ often consist of a lot of `?` characters, presumably non-ASCII text that's getting chewed up:
```
SELECT
  addons.value.description
FROM
  `moz-fx-data-shared-prod.telemetry_stable.event_v4`,
  UNNEST(environment.addons.active_addons) AS addons
WHERE
  DATE(submission_timestamp) = "2019-08-22"
LIMIT
  10
```

Row | description |  
-- | -- | --
1 | Erstellen Sie Bildschirmfotos von vollst?ndigen Webseiten oder Ausschnitten und speichern Sie diese |  
2 | Upozorn? na nov? e-maily, p?elo?? slova, p?evede m?ny a pejsek Krasty d? v?d?t, kdy? zjist? n?co nav |  
3 | Roz???en? pro pr?ci s elektronick?mi formul??i Software602 a.s. |  
4 | Po?izujte sn?mky webov?ch str?nek a ukl?dejte je do?asn? nebo natrvalo. |  
5 | Nejrychlej?? cesta na Seznam. |  
6 | ??????? ??????? ? ????????? ?? ????????? ? ?????????? ?? ???????? ??? ????????. |  
7 | McAfee? WebAdvisor |  
8 | Tw?rz wycinki i?zrzuty stron internetowych i?zapisuj je tymczasowo lub trwale. |  
9 | A very lightweight add-on that allows you to watch YouTube? videos using Flash? Player. |  
10 | Effectuez des captures d’?cran sur le Web et sauvegardez-les de mani?re temporaire ou permanente.

**Comment by whd** [comment]
This was definitely a concern I had that I (it seems wrongly) thought we discussed in the first pass of validation. It's listed under the [bonus](https://docs.google.com/document/d/13aYofoGqwv8d_zrxfxIWibHl5htcpmsKRiOlPrLdBL0/edit#heading=h.bjt3un6gu9a6) section of the document but nowhere is it mentioned that we discussed it. From my recollection @relud found this issue [as part of the 0.06% described here](https://docs.google.com/document/d/13aYofoGqwv8d_zrxfxIWibHl5htcpmsKRiOlPrLdBL0/edit#heading=h.efqxzka20llk), but unfortunately those queries and tables are on data that doesn't exist anymore.

From the email I sent "GCP Validation Work Day Summary and Notes" on April 24th, I did put a section "Ensure Unicode handling is at parity between pipelines" as a followup item, but I can't find any follow-up in the document nor or an issue here that we filed as a result. My guess is that we did in fact discover/discuss this in April but forgot to follow up on it.

**Comment by jklukas** [comment]
Here's a concrete example that shows non-ASCII characters in the raw payload, but `?` in the decoded payload.

Here's the raw payload:

```
CREATE TEMP FUNCTION
  udf_js_gunzip (input BYTES)
  RETURNS STRING
  LANGUAGE js AS """
    // converts a byte array to a string
    function binary2String(byteArray) {
        return String.fromCharCode.apply(String, byteArray);
    }
    
    // input is in base64, so it needs to be decoded
    var decodedData = atob(input);
    var compressedData = decodedData.split('').map(function(e) {
        return e.charCodeAt(0);
    });
    
    try {
      var gunzip = new Zlib.Gunzip(compressedData); 
    
      // decompress returns bytes that need to be converted into a string
      var unzipped = gunzip.decompress();
      return binary2String(unzipped);
    } catch (err) {
    try {
      return binary2String(input);
      } catch (err) {
      throw err;
      }
    }
""" OPTIONS ( library = "gs://bigquery-wasm-dev/gunzip.min.js",
    library = "gs://bigquery-wasm-dev/atob.js" );
  --
SELECT
  json_extract(udf_js_gunzip(payload),"$.environment.addons.activeAddons")
FROM
  `moz-fx-data-shared-prod.payload_bytes_raw.telemetry`
WHERE
  submission_timestamp = '2019-08-22 19:10:09.907542'
  AND x_pipeline_proxy = "2019-08-22T19:10:09.032099Z"
LIMIT
  1000
```


ow | f0_ |  
-- | -- | --
1 | {"formautofill@mozilla.org":{"version":"1.0","scope":1,"type":"extension","updateDay":18118,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":null,"name":"Form Autofill","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":18009},"screenshots@mozilla.org":{"version":"39.0.0","scope":1,"type":"extension","updateDay":18118,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Tomar clips y capturas de pantalla de la web y guardarlos temporalmente o permanentemente.","name":"Firefox Screenshots","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":18009},"fxmonitor@mozilla.org":{"version":"3.0","scope":1,"type":"extension","updateDay":18118,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":null,"name":"Firefox Monitor","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":18045},"webcompat@mozilla.org":{"version":"5.0.2","scope":1,"type":"extension","updateDay":18130,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Urgent post-release fixes for web compatibility.","name":"Web Compat","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":18130,"signedState":3},"jid1-NIfFY2CA8fy1tg@jetpack":{"version":"3.33.0","scope":1,"type":"extension","updateDay":18130,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"La extensiÃ³n mÃ¡s popular de Chrome, Â¡con mÃ¡s de 60 millones de usuarios! Bloquea anuncios de toda la","name":"AdBlock","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":18036,"signedState":2}}

And here's the decoded one:

```
SELECT
  json_extract(udf_js_gunzip(payload),"$.environment.addons.activeAddons")
FROM
  `moz-fx-data-shared-prod.payload_bytes_decoded.telemetry_telemetry__event_v4` 
WHERE
  submission_timestamp = "2019-08-22T19:10:09.032099Z"
LIMIT
  1000
```


Row | f0_ |  
-- | -- | --
1 | {"fxmonitor@mozilla.org":{"multiprocessCompatible":true,"updateDay":18118,"hasBinaryComponents":false,"blocklisted":false,"userDisabled":false,"appDisabled":false,"description":null,"installDay":18045,"type":"extension","isWebExtension":true,"version":"3.0","isSystem":true,"foreignInstall":false,"scope":1,"name":"Firefox Monitor"},"screenshots@mozilla.org":{"multiprocessCompatible":true,"updateDay":18118,"hasBinaryComponents":false,"blocklisted":false,"userDisabled":false,"appDisabled":false,"description":"Tomar clips y capturas de pantalla de la web y guardarlos temporalmente o permanentemente.","installDay":18009,"type":"extension","isWebExtension":true,"version":"39.0.0","isSystem":true,"foreignInstall":false,"scope":1,"name":"Firefox Screenshots"},"formautofill@mozilla.org":{"multiprocessCompatible":true,"updateDay":18118,"hasBinaryComponents":false,"blocklisted":false,"userDisabled":false,"appDisabled":false,"description":null,"installDay":18009,"type":"extension","isWebExtension":true,"version":"1.0","isSystem":true,"foreignInstall":false,"scope":1,"name":"Form Autofill"},"webcompat@mozilla.org":{"multiprocessCompatible":true,"updateDay":18130,"hasBinaryComponents":false,"blocklisted":false,"userDisabled":false,"appDisabled":false,"description":"Urgent post-release fixes for web compatibility.","installDay":18130,"type":"extension","isWebExtension":true,"version":"5.0.2","isSystem":true,"signedState":3,"foreignInstall":false,"scope":1,"name":"Web Compat"},"jid1-NIfFY2CA8fy1tg@jetpack":{"multiprocessCompatible":true,"updateDay":18130,"hasBinaryComponents":false,"blocklisted":false,"userDisabled":false,"appDisabled":false,"description":"La extensi?n m?s popular de Chrome, ?con m?s de 60 millones de usuarios! Bloquea anuncios de toda la","installDay":18036,"type":"extension","isWebExtension":true,"version":"3.33.0","isSystem":false,"signedState":2,"foreignInstall":false,"scope":1,"name":"AdBlock"}}

**Comment by jklukas** [comment]
I love search engines. According to https://www.i18nqa.com/debug/utf8-debug.html the string `Ã³` corresponds to the UTF-8 interpretation of `ó` encoded in Windows-1252.

Does the AWS pipeline do anything to figure out the charset used for payloads before decoding?

**Comment by whd** [comment]
/CC @trink to fact-check and correct the forthcoming analysis if necessary

> Does the AWS pipeline do anything to figure out the charset used for payloads before decoding?

I searched the archives and found https://bugzilla.mozilla.org/show_bug.cgi?id=1339834 and https://bugzilla.mozilla.org/show_bug.cgi?id=1347283#c5 which has some discourse on the nature of the previous migration's UTF8 woes. It looks like, in the AWS pipeline, we do the following:

1. Validate that all strings within the JSON payload are valid UTF8, and throw away data that can't be decoded as valid UTF8, even if it is valid JSON
1. On the analysis-side of things, we perform lossy UTF8 decoding using various downstream libraries, but data is always assumed to be UTF8

Which is to say, it is my understanding that in the AWS pipeline we do not do anything to figure out the charset used for payloads during decoding and from at least 2018 onward force all data to at a minimum be valid as UTF8. In cases where it is valid UTF8 but encoded in some other encoding the data in the data lake (heka-protobuf) retains the original encoding and downstream processing could in theory decode it in some fashion other than UTF8. In practice the two primary APIs for accessing data simply perform lossy UTF8 decoding, which would produce a result similar to what we see in BQ.

From a pipeline ingestion perspective I believe we're talking about ~ .06% of data and for a set of fields that probably weren't much investigated in the AWS pipeline. It may be worth verifying the above by finding the same/similar payloads AWS-side. 

We could perhaps enhance the GCP pipeline to try to be smart about character encoding, but I believe the current mechanism is more or less at parity with AWS. There is a minor difference in that clients in AWS could "in theory" implement custom logic to decode payloads i.e. that decoded data there is not lossy, but I doubt anybody noticed or cared. I could be off-base here though since I haven't thought much about this in a couple of years.

**Comment by jklukas** [comment]
The document_id for the example here is `076f1c9d-17e7-47ab-aba9-000a72b6e4a6` if we want to try to find it in the AWS pipeline. I assume heka files would be the only place we can see these particular activeAddOns fields.

**Comment by jklukas** [comment]
I had assumed the problem here was that the source text was encoded in Windows-1252 and we were reading it as UTF-8, but it appears to be the opposite. The debugging chart I linked to earlier says:

> the problem is being caused by UTF-8 bytes being interpreted as Windows-1252 (or ISO 8859-1) bytes

I grabbed the raw bytes from BQ and passed them through some java code to unzip and construct a string using UTF-8 charset. What I got out was the correct text ("extensión"). When I did the same but specified "Windows-1252" as the charset, I got the "extensiÃ³n" version. This isn't quite adding up to me.

**Comment by jklukas** [comment]
## UTF-16

I think I'm zeroing in on the problem. BQ expects strings to be UTF-8, so I was confused as to why BQ would be displaying corrupted characters when decoding the raw payload.

Javascript and Java both have String classes that hold UTF-16 bytes. I believe now that both our JS UDF in Bigquery and our Decoder code are suffering from reading UTF-8 bytes into UTF-16 strings.

I did some searching on how to correctly parse UTF-8 bytes into a string in JS, which is far more complicated than I expected. But I was able to modify the JS UDF to return a string that shows the correct Unicode characters in the BQ console:

```
CREATE TEMP FUNCTION
  udf_js_gunzip (input BYTES)
  RETURNS STRING
  LANGUAGE js AS """
  
  // Convert an array of UTF-8 bytes to a JavaScript String (which is UTF-16)
  // See https://weblog.rogueamoeba.com/2017/02/27/javascript-correctly-converting-a-byte-array-to-a-utf-8-string/
  function stringFromUTF8Array(data)
  {
    const extraByteMap = [ 1, 1, 1, 1, 2, 2, 3, 0 ];
    var count = data.length;
    var str = "";
    
    for (var index = 0;index < count;)
    {
      var ch = data[index++];
      if (ch & 0x80)
      {
        var extra = extraByteMap[(ch >> 3) & 0x07];
        if (!(ch & 0x40) || !extra || ((index + extra) > count))
          return null;
        
        ch = ch & (0x3F >> extra);
        for (;extra > 0;extra -= 1)
        {
          var chx = data[index++];
          if ((chx & 0xC0) != 0x80)
            return null;
          
          ch = (ch << 6) | (chx & 0x3F);
        }
      }
      
      str += String.fromCharCode(ch);
    }
    
    return str;
  }
    // converts a byte array to a string
    function binary2String(byteArray) {
        //String.fromCharCode.apply(String, byteArray);
        return stringFromUTF8Array(byteArray);
    }
    
    // input is in base64, so it needs to be decoded
    var decodedData = atob(input);
    var compressedData = decodedData.split('').map(function(e) {
        return e.charCodeAt(0);
    });
    
    try {
      var gunzip = new Zlib.Gunzip(compressedData); 
    
      // decompress returns bytes that need to be converted into a string
      var unzipped = gunzip.decompress();
      return binary2String(unzipped);
    } catch (err) {
    try {
      return binary2String(input);
      } catch (err) {
      throw err;
      }
    }
""" OPTIONS ( library = "gs://bigquery-wasm-dev/gunzip.min.js",
    library = "gs://bigquery-wasm-dev/atob.js" );
  --
SELECT
  json_extract(udf_js_gunzip(payload),"$.environment.addons.activeAddons")
FROM
  `moz-fx-data-shared-prod.payload_bytes_raw.telemetry`
WHERE
  submission_timestamp = '2019-08-22 19:10:09.907542'
  AND x_pipeline_proxy = "2019-08-22T19:10:09.032099Z"
LIMIT
  1000
```


Row | f0_ |  
-- | -- | --
1 | {"formautofill@mozilla.org":{"version":"1.0","scope":1,"type":"extension","updateDay":18118,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":null,"name":"Form Autofill","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":18009},"screenshots@mozilla.org":{"version":"39.0.0","scope":1,"type":"extension","updateDay":18118,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Tomar clips y capturas de pantalla de la web y guardarlos temporalmente o permanentemente.","name":"Firefox Screenshots","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":18009},"fxmonitor@mozilla.org":{"version":"3.0","scope":1,"type":"extension","updateDay":18118,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":null,"name":"Firefox Monitor","userDisabled":false,"appDisabled":false,…

I am going to look at seeing whether I can get the gcp-ingestion Decoder code to reproduce this behavior.

**Comment by jklukas** [comment]
UTF-16 might not exactly be the cause either, but the problem may more generically be whether the decoder is correctly handling multi-byte characters. It appears that any algorithm that converts to code points byte by byte will have the same corruption as we see when decoding using the Windows-1252 charset.

**Comment by jklukas** [comment]
In gcp-ingestion ParsePayload, we use Jackson to deserialize the unzipped raw payload bytes. We do not specify an encoding and I have just learned that Jackson includes some logic to automatically detect encoding (and may not even present public methods to control the encoding used). It chooses between UTF-8, UTF-16, or UTF-32. I now am focusing my suspicion on [Jackson's detectEncoding method](https://github.com/FasterXML/jackson-core/blob/2.9/src/main/java/com/fasterxml/jackson/core/json/ByteSourceJsonBootstrapper.java#L118) as it could well be that some of our strings are tripping the wrong encoding.

**Comment by jklukas** [comment]
Jackson docs include the statement:

> no encoding argument is taken since it can always be auto-detected as suggested by JSON RFC

**Comment by jklukas** [comment]
I've run the raw payload through the Decoder locally, and it spits out a payload with the correct uncorrupted characters, so haven't been able to reproduce the issue yet.

**Comment by jklukas** [comment]
@mreid-moz found this same record on AWS and it looks correctly encoded. See https://dbc-caf9527b-e073.cloud.databricks.com/#notebook/2667/command/168482

**Comment by whd** [comment]
For reference, the raw protobuf can be found in `s3://net-mozaws-prod-us-west-2-pipeline-data/telemetry-3/20190822/telemetry/4/event/Firefox/release/68.0.1/20190717172542/1566504498_46_ip-172-31-9-136.gz` and lsb_heka_cat with my terminal encoding set to utf8 looks like:

    name: environment.addons type: 1 representation: json value: {"activeAddons":{"formautofill@mozilla.org":{"version":"1.0","scope":1,"type":"extension","updateDay":18118,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":null,"name":"Form Autofill","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":18009},"screenshots@mozilla.org":{"version":"39.0.0","scope":1,"type":"extension","updateDay":18118,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Tomar clips y capturas de pantalla de la web y guardarlos temporalmente o permanentemente.","name":"Firefox Screenshots","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":18009},"fxmonitor@mozilla.org":{"version":"3.0","scope":1,"type":"extension","updateDay":18118,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":null,"name":"Firefox Monitor","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":18045},"webcompat@mozilla.org":{"version":"5.0.2","scope":1,"type":"extension","updateDay":18130,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Urgent post-release fixes for web compatibility.","name":"Web Compat","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":18130,"signedState":3},"jid1-NIfFY2CA8fy1tg@jetpack":{"version":"3.33.0","scope":1,"type":"extension","updateDay":18130,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"La extensi\xc3\xb3n m\xc3\xa1s popular de Chrome, \xc2\xa1con m\xc3\xa1s de 60 millones de usuarios! Bloquea anuncios de toda la","name":"AdBlock","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":18036,"signedState":2}},"theme":{"id":"default-theme@mozilla.org","blocklisted":false,"description":"A theme with the operating system color scheme.","name":"Predeterminado","userDisabled":false,"appDisabled":false,"version":"1.0","scope":4,"foreignInstall":false,"hasBinaryComponents":false,"installDay":18130,"updateDay":18118},"activePlugins":[{"name":"Shockwave Flash","version":"32.0.0.238","description":"Shockwave Flash 32.0 r0","blocklisted":false,"disabled":false,"clicktoplay":true,"mimeTypes":["application/x-shockwave-flash","application/futuresplash"],"updateDay":18125}],"activeGMPlugins":{"gmp-gmpopenh264":{"version":"1.8.1","userDisabled":false,"applyBackgroundUpdates":1},"gmp-widevinecdm":{"version":"4.10.1440.18","userDisabled":false,"applyBackgroundUpdates":1}}}

i.e. lsb_heka_cat `\x` hex-escapes the characters. We've confirmed that in AWS the heka-protobuf format retains the original client encoding and that the client API is responsible for decoding.

**Comment by jklukas** [comment]
I was not able to reproduce the `?` behavior with the Beam local Java runner, but I was able to reproduce it by launching a Dataflow job on top of an ndjson file containing just this one record.

This is making me think that something about the environment on Dataflow workers is important to what happens in json decoding/encoding. Perhaps there are locale settings in the environment or JVM that factor in here.

**Comment by jklukas** [comment]
I just posted https://github.com/mozilla/gcp-ingestion/pull/788 which switches to using Jackson for serializing the modified payload in ParsePayload. We had been relying on JSONObject's toString method, which appears to be where the corruption is occurring.

With Jackson used for both serialization and deserialization, I was able to launch a Dataflow job that did not corrupt this problematic message. So, I believe this change will fix the problem going forward.

**Comment by jklukas** [comment]
## All libraries are exonerated

I believe I now fully understand the issue here and want the record to state that neither the org.json or jackson libraries had problematic behavior in this case. The issue was our `String#getBytes()` call without specifying a charset, which left us vulnerable to using the platform default.

I did a follow-up test to verify that we indeed correct output if we use `json.toString().getBytes("UTF-8")` and submit the job to Dataflow.

Jackson does what it claims to, inferring the encoding of input bytes when deserializing, and always using UTF-8 when serializing.

org.json seems to have a reasonable algorithm for serializing objects to string and leaves it up to the user to convert that string into bytes.

**Comment by jklukas** [comment]
The fix was deployed on Friday and it looks like it's working:

```
SELECT
  addons.value.description
FROM
  `moz-fx-data-shared-prod.telemetry_stable.event_v4`,
  UNNEST(environment.addons.active_addons) AS addons
WHERE
  DATE(submission_timestamp) = "2019-09-01"
  AND addons.value.description LIKE '%\?%'
LIMIT
  10
```


Row | description |  
-- | -- | --
1 | Kiss the annoying "Video paused. Continue watching?" confirmation goodbye! |  
2 | Hledáte youtube video downloader? Nainstalovat YouTube Downloader a stáhněte si video z YouTube. |  
3 | Hledáte youtube video downloader? Nainstalovat YouTube Downloader a stáhněte si video z YouTube. |  
4 | Let's try to re-color the tabs. Shall we? Currently only colors the selected tab due to https://bugz |  
5 | Willst du wissen, wo du Cashback für deine Online-Einkäufe bekommen kannst? Das geht mit dem Cashbac |  
6 | Would you still like to be able to enjoy Youtube's old look? Button "Restore old design" disappeared |  
7 | Would you still like to be able to enjoy Youtube's old look? Button "Restore old design" disappeared |  
8 | Would you still like to be able to enjoy Youtube's old look? Button "Restore old design" disappeared |  
9 | Would you still like to be able to enjoy Youtube's old look? Button "Restore old design" disappeared |  
10 | Want to learn more about yoga?

**Comment by tdsmith** [comment]
Thanks for the investigation and the fix!

**Comment by jklukas** [comment]
I'll plan to send out an announcement tomorrow to data users about the fix and the epoch of data affected.
