### ISSUE TITLE
Warn on use of JSONObject#toString

### ISSUE THREAD

**Issue by jklukas** [mozilla/gcp-ingestion#789]
As a follow-up to https://github.com/mozilla/gcp-ingestion/pull/788, we should make sure we don't accidentally use JSONObject#toString for serializing JSON in the future. There are likely ways to enforce such things in a Java project, but I don't know specifically how to do so.

**Comment by jklukas** [comment]
cc @relud

**Comment by relud** [comment]
we could extend JSONObject with our own implementation that overrides `.toString` to throw an exception (or use jackson, but then we have to be more careful about recursively using our implementation).

**Comment by jklukas** [comment]
Per #811 I am going to refactor so that we use JSONObject in only one class, and otherwise rely on Jackson's `JsonObject` for ingestion-beam.
