### ISSUE TITLE
Investigate telemetry bq sink job failure

### ISSUE THREAD

**Issue by whd** [mozilla/gcp-ingestion#830]
/CC @mreid-moz 

[Job in question](https://console.cloud.google.com/dataflow/jobsDetail/locations/us-west1/jobs/2019-09-13_19_42_29-3073605960826792613?project=moz-fx-data-beam-prod-11f7&organizationId=442341870013&supportedpurview=project&walkthrough_tutorial_id=dataflow_index)

It wasn't clear to me at the time since I busy dealing with making sure we could process the backfill it generated, but the error that caused this job to stop processing data is pretty obviously:

    java.lang.RuntimeException: org.apache.beam.sdk.util.UserCodeException: java.io.IOException: com.google.api.client.googleapis.json.GoogleJsonResponseException: 410 Gone
    {
      "code" : 503,
      "errors" : [ {
        "domain" : "global",
        "message" : "Backend Error",
        "reason" : "backendError"
      } ],
      "message" : "Backend Error"
    }
            org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowsParDoFn$1.output(GroupAlsoByWindowsParDoFn.java:184)
            org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowFnRunner$1.outputWindowedValue(GroupAlsoByWindowFnRunner.java:102)
            org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.ReduceFnRunner.lambda$onTrigger$1(ReduceFnRunner.java:1057)
            org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.ReduceFnContextFactory$OnTriggerContextImpl.output(ReduceFnContextFactory.java:438)
            org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SystemReduceFn.onTrigger(SystemReduceFn.java:125)
            org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.ReduceFnRunner.onTrigger(ReduceFnRunner.java:1060)
            org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.ReduceFnRunner.emit(ReduceFnRunner.java:930)
            org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.ReduceFnRunner.processElements(ReduceFnRunner.java:368)
            org.apache.beam.runners.dataflow.worker.StreamingGroupAlsoByWindowViaWindowSetFn.processElement(StreamingGroupAlsoByWindowViaWindowSetFn.java:94)
            org.apache.beam.runners.dataflow.worker.StreamingGroupAlsoByWindowViaWindowSetFn.processElement(StreamingGroupAlsoByWindowViaWindowSetFn.java:42)
            org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowFnRunner.invokeProcessElement(GroupAlsoByWindowFnRunner.java:115)
            org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowFnRunner.processElement(GroupAlsoByWindowFnRunner.java:73)
            org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.LateDataDroppingDoFnRunner.processElement(LateDataDroppingDoFnRunner.java:80)
            org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowsParDoFn.processElement(GroupAlsoByWindowsParDoFn.java:134)
            org.apache.beam.runners.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:44)
            org.apache.beam.runners.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:49)
            org.apache.beam.runners.dataflow.worker.util.common.worker.ReadOperation.runReadLoop(ReadOperation.java:201)
            org.apache.beam.runners.dataflow.worker.util.common.worker.ReadOperation.start(ReadOperation.java:159)
            org.apache.beam.runners.dataflow.worker.util.common.worker.MapTaskExecutor.execute(MapTaskExecutor.java:77)
            org.apache.beam.runners.dataflow.worker.StreamingDataflowWorker.process(StreamingDataflowWorker.java:1295)
            org.apache.beam.runners.dataflow.worker.StreamingDataflowWorker.access$1000(StreamingDataflowWorker.java:149)
            org.apache.beam.runners.dataflow.worker.StreamingDataflowWorker$6.run(StreamingDataflowWorker.java:1028)
            java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
            java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
            java.lang.Thread.run(Thread.java:745)
    Caused by: org.apache.beam.sdk.util.UserCodeException: java.io.IOException: com.google.api.client.googleapis.json.GoogleJsonResponseException: 410 Gone
    {
      "code" : 503,
      "errors" : [ {
        "domain" : "global",
        "message" : "Backend Error",
        "reason" : "backendError"
      } ],
      "message" : "Backend Error"
    }
            org.apache.beam.sdk.util.UserCodeException.wrap(UserCodeException.java:34)
            org.apache.beam.sdk.io.gcp.bigquery.WriteGroupedRecordsToFiles$DoFnInvoker.invokeProcessElement(Unknown Source)
            org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:214)
            org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.processElement(SimpleDoFnRunner.java:176)
            org.apache.beam.runners.dataflow.worker.StreamingSideInputDoFnRunner.processElement(StreamingSideInputDoFnRunner.java:73)
            org.apache.beam.runners.dataflow.worker.SimpleParDoFn.processElement(SimpleParDoFn.java:330)
            org.apache.beam.runners.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:44)
            org.apache.beam.runners.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:49)
            org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowsParDoFn$1.output(GroupAlsoByWindowsParDoFn.java:182)
            org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowFnRunner$1.outputWindowedValue(GroupAlsoByWindowFnRunner.java:102)
            org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.ReduceFnRunner.lambda$onTrigger$1(ReduceFnRunner.java:1057)
            org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.ReduceFnContextFactory$OnTriggerContextImpl.output(ReduceFnContextFactory.java:438)
            org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SystemReduceFn.onTrigger(SystemReduceFn.java:125)
            org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.ReduceFnRunner.onTrigger(ReduceFnRunner.java:1060)
            org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.ReduceFnRunner.emit(ReduceFnRunner.java:930)
            org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.ReduceFnRunner.processElements(ReduceFnRunner.java:368)
            org.apache.beam.runners.dataflow.worker.StreamingGroupAlsoByWindowViaWindowSetFn.processElement(StreamingGroupAlsoByWindowViaWindowSetFn.java:94)
            org.apache.beam.runners.dataflow.worker.StreamingGroupAlsoByWindowViaWindowSetFn.processElement(StreamingGroupAlsoByWindowViaWindowSetFn.java:42)
            org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowFnRunner.invokeProcessElement(GroupAlsoByWindowFnRunner.java:115)
            org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowFnRunner.processElement(GroupAlsoByWindowFnRunner.java:73)
            org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.LateDataDroppingDoFnRunner.processElement(LateDataDroppingDoFnRunner.java:80)
            org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowsParDoFn.processElement(GroupAlsoByWindowsParDoFn.java:134)
            org.apache.beam.runners.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:44)
            org.apache.beam.runners.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:49)
            org.apache.beam.runners.dataflow.worker.util.common.worker.ReadOperation.runReadLoop(ReadOperation.java:201)
            org.apache.beam.runners.dataflow.worker.util.common.worker.ReadOperation.start(ReadOperation.java:159)
            org.apache.beam.runners.dataflow.worker.util.common.worker.MapTaskExecutor.execute(MapTaskExecutor.java:77)
            org.apache.beam.runners.dataflow.worker.StreamingDataflowWorker.process(StreamingDataflowWorker.java:1295)
            org.apache.beam.runners.dataflow.worker.StreamingDataflowWorker.access$1000(StreamingDataflowWorker.java:149)
            org.apache.beam.runners.dataflow.worker.StreamingDataflowWorker$6.run(StreamingDataflowWorker.java:1028)
            java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
            java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
            java.lang.Thread.run(Thread.java:745)
    Caused by: java.io.IOException: com.google.api.client.googleapis.json.GoogleJsonResponseException: 410 Gone
    {
      "code" : 503,
      "errors" : [ {
        "domain" : "global",
        "message" : "Backend Error",
        "reason" : "backendError"
      } ],
      "message" : "Backend Error"
    }
            com.google.cloud.hadoop.util.AbstractGoogleAsyncWriteChannel.waitForCompletionAndThrowIfUploadFailed(AbstractGoogleAsyncWriteChannel.java:367)
            com.google.cloud.hadoop.util.AbstractGoogleAsyncWriteChannel.close(AbstractGoogleAsyncWriteChannel.java:238)
            org.apache.beam.sdk.io.gcp.bigquery.TableRowWriter.close(TableRowWriter.java:80)
            org.apache.beam.sdk.io.gcp.bigquery.WriteGroupedRecordsToFiles.processElement(WriteGroupedRecordsToFiles.java:71)
    Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 410 Gone
    {
      "code" : 503,
      "errors" : [ {
        "domain" : "global",
        "message" : "Backend Error",
        "reason" : "backendError"
      } ],
      "message" : "Backend Error"
    }
            com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:150)
            com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
            com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
            com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:512)
            com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:432)
            com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:549)
            com.google.cloud.hadoop.util.AbstractGoogleAsyncWriteChannel$UploadOperation.call(AbstractGoogleAsyncWriteChannel.java:301)
            java.util.concurrent.FutureTask.run(FutureTask.java:266)
            java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
            java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
            java.lang.Thread.run(Thread.java:745)

It's not clear to me what resource disappeared, and whether it was perhaps transient. I would not expect a "gone" to be returned from GCP unless a resource was deleted, but this occurred during a time when no resources were being modified. There was a table delete that occurred a few days earlier for https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/406, but that was deployed many days before this error and the decoder and bq sinks were both updated to reflect it (see the schemas_build_id tag for the precise ref being used in this job). The latest schema change that occured was https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/410 which was deployed on the 13th.

**Comment by whd** [comment]
While investigating some voice tables not being created as expected @sunahsuh and I noticed that we pathed one of the files incorrectly i.e. [this file](https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/master/schemas/telemetry/voice/voice-feedback.4.schema.json) should be in a [`voice-feedback` directory](https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/412), causing the table management logic to fail to create the table. I'm wondering if the following is plausible:

1. we deploy the schemas with the incorrect path
1. a test client in Australia or something sends a voice-feedback ping
1. the decoder ignores the directory name (it is redundant by some measures) in processing and successfully decodes the data as valid
1. the bq sink similarly ignores the directory name and attempts to write the data to a table which doesn't exist, halting processing

@jklukas can you comment on how the current pipeline might handle the above pathing?

**Comment by jklukas** [comment]
The current pipeline checks for doctype existence based on directories. So I would expect the pipeline to reject the message and say the doctype doesn't exist for the case where there is no directory corresponding to the doctype name.

**Comment by whd** [comment]
Ok, so we're still in the dark as to what the 410 error was about, but good to know the pipeline acted in the way I would have expected it to in this case.

**Comment by whd** [comment]
Google has supposed this has something to do with a known GCS bucket issue with Dataflow. While this job doesn't primarily output to GCS, it uses GCS buckets as part of its internal operation. Google is continuing their investigation into the matter.

**Comment by whd** [comment]
From Google:

The Dataflow team determined the root cause for the stuck job was due to an out of memory issue. The 410 errors may have been a side effect of the OOM issue.

The team suggested two viable options here that may mitigate this OOM issue. First, you may specify a high memory machine type for your workers. You can do this by specifying your machine type in your PipelineOptions object[1] using the --worker_machine_type flag. A list of high memory machines can be found here[2].

The alternative approach here is to adjust the withMaxFilesPerBundle parameter. This essentially allows you to set the maximum number of files that a single worker can write concurrently before shuffling the data. The default value of withMaxFilesPerBundle is 20 and the team recommends testing with a lower value (ex. 10 might be a good starting point) to reduce memory load. There are some caveats to this approach, so reviewing the documentation here[3] is advisable. Please let me know if this helps or if you have any remaining questions or concerns.

[1] https://cloud.google.com/dataflow/docs/guides/specifying-exec-params#setting-other-cloud-pipeline-options
[2] https://cloud.google.com/compute/docs/machine-types#n1_high-memory_machine_types
[3] https://github.com/apache/beam/blob/0d2fbf205103de92540b6b1bdb7050495cfdf8dd/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIO.java#L2166

**Comment by whd** [comment]
This occurred again this morning, though with the structured bq sink this time. If it continues to occur with increased frequency I will prioritize tuning parameters to fix it, but I don't want to waste too much money here if I can help it since we're switching to k8s-based sinks anyway.

**Comment by relud** [comment]
>  I don't want to waste too much money here if I can help it since we're switching to k8s-based sinks anyway.

we have now switched
