### ISSUE TITLE
BQ error output due to rate limit on BQ API

### ISSUE THREAD

**Issue by jklukas** [mozilla/gcp-ingestion#938]
We're hitting this again. See `gs://moz-fx-data-prod-data/telemetry-decoded_bq-sink/error/2019-10-22/13/error-2019-10-22T13-50-00.000Z-2019-10-22T14-00-00.000Z-0-00059-of-00060.ndjson.gz` for example.

```
"exception_class":"com.google.common.util.concurrent.UncheckedExecutionException",
"normalized_app_name":"Firefox",
"document_id":"47aa366d-c24f-4dce-bf59-7292be4fdd12",
"document_version":"4",
"normalized_os_version":"6.1",
"client_id":"046f741a-3605-4b5d-83e5-cfa2766d7208",
"stack_trace_cause_2":"[com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:150), com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113), com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40), com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:401), com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1097), com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:499), com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:432), com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:549), com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.getDataset(...",
"stack_trace_cause_1":"[com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.translate(HttpBigQueryRpc.java:100), com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.getDataset(HttpBigQueryRpc.java:112), com.google.cloud.bigquery.BigQueryImpl$5.call(BigQueryImpl.java:289), com.google.cloud.bigquery.BigQueryImpl$5.call(BigQueryImpl.java:286), com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105), com.google.cloud.RetryHelper.run(RetryHelper.java:76), com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50), com.google.cloud.bigquery.BigQueryImpl.getDataset(BigQueryImpl.java:285), com.google.cloud.bigquery.BigQueryImpl.getDataset(BigQueryImpl.java:276), com.mozilla.telemetry.transforms.KeyByBigQueryTableDestination.lambda$getTableDestination$2(KeyByBigQueryTableDestination.java:94), com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4878), com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529), com.google.common.cache.LocalCache$Segmen...",
"error_type":"KeyByBigQueryTableDestination",
"document_type":"modules",
"error_message":"com.google.common.util.concurrent.UncheckedExecutionException: com.google.cloud.bigquery.BigQueryException: Exceeded rate limits: too many api requests per user per method for this user_method. For more information, see https://cloud.google.com/bigquery/troubleshooting-errors",
```

**Comment by jklukas** [comment]
cc @whd

**Comment by whd** [comment]
Previously discussed in https://github.com/mozilla/gcp-ingestion/issues/651, but likely a different cause this time. Assuming we keep all the relevant data in the error messages, perhaps re-running these through the bq sink (filtered on this exact error type if necessary) is the easiest thing to do.

**Comment by jklukas** [comment]
Running a Dataflow job now to try reprocessing this data.

**Comment by jklukas** [comment]
Assuming the job for 10/22 goes well, I will plan to kick off a job to reprocess all decoded bq sink errors for 2019-09 and 2019-10.

**Comment by whd** [comment]
I'm seeing `gs://moz-fx-data-prod-data/telemetry-decoded_bq-sink/error/2019-10-` stop at hour 19 when #939 was deployed so live data should no longer be hitting this. There are  other unchecked execution exceptions such as https://github.com/mozilla/gcp-ingestion/issues/894 that depending on how the backfill works should also be resolved (in theory, any bq error output is bad and should be re-processable except perhaps #776). In fact, hopefully catching `UncheckedExecution` resolves https://github.com/mozilla/gcp-ingestion/issues/667 which is the more general original issue.

**Comment by jklukas** [comment]
The job for 10/22 succeeded. Kicking off the rest of the days now.

**Comment by jklukas** [comment]
These jobs were successful. I've copied the results into the prod live tables, and will finally run copy_dedupe on the affected days to recreate the stable table partitions.

Only a few days were actually affected:


Row | date | n |  
-- | -- | -- | --
1 | 2019-09-02 | 730 |  
2 | 2019-09-15 | 10679 |  
3 | 2019-09-26 | 57713 |  
4 | 2019-10-02 | 5 |  
5 | 2019-10-22 | 3768260 |  
6 | 2019-10-23 | 4529572

There several other days with errors in GCS, but it looks like those are all single PayloadTooLarge incidents. The above six days are the ones with API rate limiting problems.

**Comment by jklukas** [comment]
In Airflow, I reset the copy_dedupe jobs for main for 2019-10-22 and 2019-10-23 and those are starting to run.

**Comment by whd** [comment]
We should run the same backfill for the structured live sink, as per https://github.com/mozilla/gcp-ingestion/issues/894 structured is affected as well (I noticed this because the date in that issue is not listed in your table). We can close that issue as well once this is complete as it is a subset of what this covers.

**Comment by jklukas** [comment]
Errors are backfilled now for all `telemetry-decoded_bq-sink`. I may need a more repeatable process to make it feasible to get all the other cases.

**Comment by whd** [comment]
Now it also occurs to me that the order of operations is relevant from a backfill perspective, in particular:

1. `decoded_bq-sink-raw` -> `payload_bytes_decoded` needs to occur before backfills that use `payload_bytes_decoded`
1. `error_bq-sink-raw` -> `payload_bytes_error` should in theory only contain decode errors, so our error information e.g. `monitoring` views will be missing some data, but otherwise don't really matter
1. `decoded_bq-sink` -> live/stable tables, which is what has been processed and will fix live/stable tables independent of `payload_bytes_decoded`

Which is to say the backfill in  https://bugzilla.mozilla.org/show_bug.cgi?id=1590559 may be dependent on (1) above, except if it's using `payload_bytes_raw`. On that score, the `raw raw` sinks output error data to a different bucket `gs://moz-fx-data-prod-landfill/`, but there are no errors for these sinks. This seemed suspicious to me so I double checked the permissions (`raw raw` sinks use a different service account that has write permission to that bucket) and they're correct, so `payload_bytes_raw` appears to have been unaffected by this rate limit issue (or any issues thankfully) for some reason.

**Comment by jklukas** [comment]
I just successfully completed backfills for `gs://moz-fx-data-prod-data/structured-decoded_bq-sink-raw/` and `gs://moz-fx-data-prod-data/telemetry-decoded_bq-sink-raw/` into payload_bytes_decoded tables. This unblocks me from running a backfill from telemetry decoded bytes into live/stables tables to get schema updates.

**Comment by jklukas** [comment]
Of note, since implementing the BubbleUpException, I see no new errors for the bq sinks except for a total of 12 telemetry messages that hit PayloadTooLargeException.

**Comment by jklukas** [comment]
I believe we've covered everything here. We backfilled from GCS into payload_bytes_decoded for both telemetry and for structured, then I separately did a backfill of 2019-09-01 through 2019-10-17 from payload_bytes_decoded to stable tables, which obviates the need for backfilling from live sink errors for those days.

Is stub_installer worth looking into?
