### ISSUE TITLE
Investigate stub installer pipeline family errors

### ISSUE THREAD

**Issue by whd** [mozilla/gcp-ingestion#945]
This is non-urgent since stub installer isn't actively receiving traffic in GCP yet and the issue is actually unrelated to stub installer itself.

[Here](https://github.com/mozilla-services/cloudops-infra/blob/master/projects/data-ingestion/k8s/values/app.yaml#L29) is the edge routing configuration, reproduced for readability here:

    [
      ["/stub/<suffix:path>", "projects/moz-fx-data-shared-prod/topics/stub_installer-raw", ["GET"]],
      ["/submit/telemetry/<_id:string>/pioneer-study/<suffix:path>", "projects/moz-fx-data-shared-prod/topics/telemetry-raw"],
      ["/submit/telemetry/<suffix:path>", "projects/moz-fx-data-shared-prod/topics/telemetry-raw"],
      ["/submit/sslreports", "projects/moz-fx-data-shared-prod/topics/tls_error_reports-raw", ["POST", "PUT"]],
      ["/submit/<suffix:path>", "projects/moz-fx-data-shared-prod/topics/structured-raw", ["POST", "PUT"]],
      ["/submit", "projects/moz-fx-data-shared-prod/topics/stub_installer-raw"]
    ]

In it the final two rules are supposed to translate (using regex) to:

1. `/submit/.*` goes to the structured pipeline family
2. `/submit$` (no trailing slash) goes to the stub installer pipeline family

After seeing some data being routed to stub installer it's my (potentially incorrect) understanding that the rules actually mean:

1. `/submit/.+` goes to the structured pipeline family
2. `/submit[^/].*` goes to the stub installer pipeline family

This is because empirically `/submit/` (trailing / but not other suffix) appears to be going to the stub installer topic.

At any rate, parsing `/submit/` should fail at the decoder for any pipeline it's finally routed to (and in fact I believe this is the case, the original error that brought me to investigate this was `gs://moz-fx-data-prod-data/stub_installer-error_bq-sink-raw/`, which is error data that was hitting #938).

An interesting potential edge case uncovered is when republishing raw/unsanitized records, we can hit null pointer exceptions when parsing bad URIs e.g. `gs://moz-fx-data-prod-data/stub_installer-raw_republisher/error/2019-10-24/17/error-2019-10-24T17-50-00.000Z-2019-10-24T18-00-00.000Z-0-00019-of-00060.ndjson.gz`. This only affects bad data presently, but that bad data won't be republished to stage so it's perhaps worth fixing. It may also affect stub installer data when we do send that, or it could also be a misunderstanding on my part or misconfiguration somewhere.

**Comment by relud** [comment]
> After seeing some data being routed to stub installer it's my (potentially incorrect) understanding that the rules actually mean:
> 
>     1. `/submit/.+` goes to the structured pipeline family
> 
>     2. `/submit[^/].*` goes to the stub installer pipeline family
> 
> 
> This is because empirically `/submit/` (trailing / but not other suffix) appears to be going to the stub installer topic.

If I remember correctly I think sanic would actually parse this config as:

1. `/submit/.+` goes to the structured pipeline family
2. `/submit/?` goes to the stub installer pipeline family

unless we set `strict_slashes=True` as in #947

**Comment by whd** [comment]
#947 will resolve the stub-installer specific part of this. I've filed #964 for the republisher issue which is actually unrelated to stub installer specifically.
