### ISSUE TITLE
Coerce all values to match expected types in BigQuery sink

### ISSUE THREAD

**Issue by jklukas** [mozilla/gcp-ingestion#948]
Currently, we coerce values to string where string is expected. This allows us to handle userPrefs and histograms.

We have run into an issue where we sometimes see a boolean show up in an int column (see https://bugzilla.mozilla.org/show_bug.cgi?id=1590559) and should handle that case, and perhaps the more general case of values not matching expectations.

We could cast these booleans to integers or we could insert null in these situations. Perhaps if we insert null we should put the value in additionalProperties.

**Comment by relud** [comment]
> We could cast these booleans to integers or we could insert null in these situations. Perhaps if we insert null we should put the value in additionalProperties.

+1 to cast if possible, otherwise insert null and put the value in `additional_properties`

**Comment by jklukas** [comment]
This is done in #951
