### ISSUE TITLE
Test bigquery output in ingestion-beam

### ISSUE THREAD

**Issue by relud** [mozilla/gcp-ingestion#95]
bq doesn't have an emulator, so i think this will have two parts.

1) use a fake http service and hit localhost. may not work.
2) use cloud-build on restricted branches and test actual bq output. needs to generate unique table names and reliably clean up all resources after running.

**Comment by jklukas** [comment]
[Google's recommendations for testing integration with BigQuery](https://github.com/googleapis/google-cloud-java/blob/master/TESTING.md#testing-code-that-uses-bigquery) are to create a test project and use their `RemoteBigQueryHelper` to handle some of the boilerplate of generating a dataset name and forcing deletion of the dataset when done testing.

It may be worth starting with that and observing how much latency is involved for setting up and tearing down the dataset. If it's reasonably quick, we may not need to add in the extra complexity of mocking locally.

**Comment by jklukas** [comment]
@relud - Why would we be getting cloud-build into the mix here? Does that significantly ease the situation for managing credentials and permissions? Is there also a reasonable option here for running tests that hit BigQuery via an additional CircleCI job?

**Comment by jklukas** [comment]
I've provisioned a GCP project and am testing out how tests look hitting real BQ. Results so far are very promising; there's no noticeable lag so far for creating a dataset in BQ. We'll see how latency goes for creating a table and making a query.

**Comment by relud** [comment]
cloud build seemed like the easiest way to handle credentials, with a potential benefits of preserving certain test resources and being able to access restricted data. I'm not picky about actually using it, was just an idea. It sounds like provisioning temporary stuff is sufficiently low latency as to not worry about preserving resources. Looking forward to see what you've got for this :)

**Comment by jklukas** [comment]
Broke out additional testing need to #191
