### ISSUE TITLE
Support reading nested metadata from payload_bytes_decoded

### ISSUE THREAD

**Issue by jklukas** [mozilla/gcp-ingestion#955]
We currently can't run the Sink job on top of payload_bytes_decoded because we drop the nested metadata struct that contains doctype, etc. which is important for routing to destination tables.

**Comment by relud** [comment]
don't the payload_bytes_decoded tables already have that information encoded in the table name? could the table name be used to restore the necessary metadata, rather than decoding the payload?

**Comment by jklukas** [comment]
Yes, we could also recover these stats from the table name. But the decoded bytes tables also have a top-level `metadata` struct that we currently throw away when reading from those tables. So, this issue is not about descending into the payload to recover metadata (which the Decoder will do), but rather about handling the `metadata` struct that appears as a field in the table.
