### ISSUE TITLE
Data quality monitoring: alert if counts differ in live vs. stable vs. decoded bytes

### ISSUE THREAD

**Issue by jklukas** [mozilla/gcp-ingestion#983]
Discussed with @acmiyaguchi 

We could write daily queries or even hourly queries to check that expected counts match between different tables in the pipeline.

Things we could check hourly:

- `payload_bytes_decoded` count should exactly match live tables
- `payload_bytes_raw` count should exactly match `payload_bytes_decoded` + `payload_bytes_error`

Things we could check nightly:

- count of distinct document_ids should match between `payload_bytes_decoded`, live, and stable tables

We will expect some loading latency between these different sources, but that should generally be under 10 minutes. For hourly checks, we should be safe to check the period between 1 hour and 2 hours ago. We could kick off checks for daily counts right after copy_deduplicate.

cc @relud @whd

**Comment by jklukas** [comment]
We do now compare unique document counts between decoded, live, and stable tables now in our Monday platform health check-in meetings.

**Comment by relud** [comment]
@jklukas did you mean to close this?

**Comment by jklukas** [comment]
We don't fully meet the scope of the original issue, so we could leave this open to document the ideas around checking raw counts vs. decoded + error. But our dedupe behavior now means that relationship is no longer expected to be true. So yes, closing.
